import type { NormalizedFinancials, NormalizedPeriod } from '../types/normalized'
const present = (...v: (number | null)[]) => v.every((x) => x !== null)
export const grossMargin = (p: NormalizedFinancials) => present(p.grossProfit, p.revenue) && p.revenue !== 0 ? p.grossProfit! / p.revenue! : null
export const operatingMargin = (p: NormalizedFinancials) => present(p.operatingIncome, p.revenue) && p.revenue !== 0 ? p.operatingIncome! / p.revenue! : null
export const netDebtExLeases = (p: NormalizedFinancials) => present(p.shortTermDebt, p.longTermDebt, p.cashAndCashEquivalents, p.shortTermInvestments) ? p.shortTermDebt! + p.longTermDebt! - p.cashAndCashEquivalents! - p.shortTermInvestments! : null
export const netDebtIncludingLeases = (p: NormalizedFinancials) => present(netDebtExLeases(p), p.leaseLiabilitiesCurrent, p.leaseLiabilitiesNonCurrent) ? netDebtExLeases(p)! + p.leaseLiabilitiesCurrent! + p.leaseLiabilitiesNonCurrent! : null
export const freeCashFlow = (p: NormalizedFinancials) => present(p.cashFlowFromOperations, p.capex) ? p.cashFlowFromOperations! - p.capex! : null
export const retailerAdjustedFcf = (p: NormalizedFinancials) => present(p.cashFlowFromOperations, p.capex, p.totalLeaseCashPayments) ? p.cashFlowFromOperations! - p.capex! - p.totalLeaseCashPayments! : null
export const basisPointChange = (from: number | null, to: number | null) => from !== null && to !== null ? (to - from) * 10000 : null
export const fcfYield = (fcf: number | null, marketCapMillions: number | null) => fcf !== null && marketCapMillions !== null && marketCapMillions !== 0 ? fcf / marketCapMillions : null
export const cashConversion = (fcf: number | null, netIncome: number | null) => fcf !== null && netIncome !== null && netIncome !== 0 ? fcf / netIncome : null
export function ttm(periods: NormalizedPeriod[]): NormalizedPeriod | null { const q = periods.filter((p) => p.periodType === 'QUARTERLY').sort((a, b) => a.periodEnd.localeCompare(b.periodEnd)); if (q.length < 4) return null; const last = q.slice(-4), sum = (k: keyof NormalizedFinancials) => { const values = last.map((p) => p[k]); return values.every((v) => typeof v === 'number') ? values.reduce((a, v) => a + (v as number), 0) : null }; const balance = (k: keyof NormalizedFinancials) => last[3][k] as number | null; return { ...last[3], id: `${last[3].companyId}-TTM-${last[3].periodEnd}`, periodType: 'TTM', periodStart: last[0].periodStart, sourceIds: [...new Set(last.flatMap((p) => p.sourceIds))], dataStatus: last.some((p) => p.dataStatus === 'INCOMPLETE') ? 'INCOMPLETE' : last[3].dataStatus, revenue: sum('revenue'), operatingIncome: sum('operatingIncome'), netIncome: sum('netIncome'), cashFlowFromOperations: sum('cashFlowFromOperations'), capex: sum('capex'), cashAndCashEquivalents: balance('cashAndCashEquivalents'), inventory: balance('inventory'), equity: balance('equity') } }
