import { describe, expect, it } from 'vitest'
import { deleteResearchNote, normalizeResearchNote, readResearchNotes, saveResearchNote, writeResearchNotes } from './researchNotes'
import { toggleWatchlist } from './watchlist'
const universe = ['castro', 'fox']
const storage = () => { const s: any = { data: '' }; s.getItem = () => s.data; s.setItem = (_: string, value: string) => { s.data = value }; return s }
describe('research note storage', () => {
  it('handles empty, malformed, invalid and duplicate records safely', () => { expect(readResearchNotes(storage(), universe)).toEqual([]); const s: any = { getItem: () => '{bad' }; expect(readResearchNotes(s, universe)).toEqual([]); expect(normalizeResearchNote({ companyId: 'bad', thesis: 'x' }, universe)).toBeNull(); const notes = readResearchNotes({ getItem: () => JSON.stringify([{ companyId: 'CASTRO', thesis: ' old ', updatedAt: '2025' }, { companyId: 'castro', thesis: 'new', updatedAt: '2026' }]) } as any, universe); expect(notes[0].thesis).toBe('new') })
  it('trims, bounds and saves/updates/deletes', () => { const s = storage(); const note: any = { companyId: 'CASTRO', thesis: ' thesis ', catalysts: Array.from({ length: 25 }, (_, i) => ` ${i} `), risks: [], questions: [], generalNotes: ' notes ', updatedAt: new Date().toISOString() }; let notes = saveResearchNote(s, [], note, universe); expect(notes[0].thesis).toBe('thesis'); expect(notes[0].catalysts).toHaveLength(20); notes = saveResearchNote(s, notes, { ...note, thesis: 'updated', catalysts: [] }, universe); expect(notes[0].thesis).toBe('updated'); expect(deleteResearchNote(s, notes, 'castro', universe)).toEqual([]) })
  it('fails safely on write errors', () => { const result = writeResearchNotes({ setItem: () => { throw Error('quota') } } as any, [{ companyId: 'fox', thesis: 'x', catalysts: [], risks: [], questions: [], generalNotes: '', updatedAt: new Date().toISOString() }], universe); expect(result).toHaveLength(1) })
  it('keeps research and watchlist persistence independent', () => { const researchStorage = storage(); const watchStorage = storage(); const note = { companyId: 'fox', thesis: 'keep', catalysts: [], risks: [], questions: [], generalNotes: '', updatedAt: new Date().toISOString() }; const notes = saveResearchNote(researchStorage, [], note, universe); expect(toggleWatchlist(watchStorage, ['fox'], 'fox', universe)).toEqual([]); expect(readResearchNotes(researchStorage, universe)).toHaveLength(1); toggleWatchlist(watchStorage, [], 'fox', universe); expect(deleteResearchNote(researchStorage, notes, 'fox', universe)).toEqual([]); expect(JSON.parse(watchStorage.data)).toEqual(['fox']) })
})
