import { describe, expect, it } from 'vitest'
import { decryptWorkspaceBackup, encryptWorkspaceBackup, ENCRYPTED_BACKUP_SCHEMA, MAX_PBKDF2_ITERATIONS, MIN_PBKDF2_ITERATIONS, validateEncryptedEnvelope } from './workspaceBackupCrypto'
const backup: any = { schema: 'israel-stocks.workspace-backup', version: 1, exportedAt: new Date().toISOString(), appData: { watchlist: ['sano'], savedComparisons: [], researchNotes: [{ companyId: 'sano', thesis: 'private thesis', catalysts: [], risks: [], questions: [], generalNotes: '', updatedAt: new Date().toISOString() }], reviewState: [] } }
describe('encrypted workspace backup', () => {
  it('round trips and keeps plaintext out of the envelope', async () => { const x = await encryptWorkspaceBackup(backup, 'correct horse battery'); expect(x.schema).toBe(ENCRYPTED_BACKUP_SCHEMA); expect(JSON.stringify(x)).not.toContain('private thesis'); expect(JSON.stringify(x)).not.toContain('correct horse'); await expect(decryptWorkspaceBackup(x, 'correct horse battery')).resolves.toMatchObject(backup) })
  it('uses fresh salt and IV', async () => { const a = await encryptWorkspaceBackup(backup, 'correct horse battery'); const b = await encryptWorkspaceBackup(backup, 'correct horse battery'); expect(a.crypto.salt).not.toBe(b.crypto.salt); expect(a.crypto.iv).not.toBe(b.crypto.iv); expect(a.ciphertext).not.toBe(b.ciphertext) })
  it('fails safely for wrong password and tampering', async () => { const x = await encryptWorkspaceBackup(backup, 'correct horse battery'); await expect(decryptWorkspaceBackup(x, 'wrong password')).rejects.toThrow('Could not decrypt'); const y = { ...x, ciphertext: `${x.ciphertext.slice(0, -2)}AA` }; await expect(decryptWorkspaceBackup(y, 'correct horse battery')).rejects.toThrow('Could not decrypt') })
  it('validates crypto metadata and iteration bounds', async () => { const x = await encryptWorkspaceBackup(backup, 'correct horse battery'); expect(() => validateEncryptedEnvelope({ ...x, crypto: { ...x.crypto, iterations: MIN_PBKDF2_ITERATIONS - 1 } })).toThrow(); expect(() => validateEncryptedEnvelope({ ...x, crypto: { ...x.crypto, iterations: MAX_PBKDF2_ITERATIONS + 1 } })).toThrow(); expect(() => validateEncryptedEnvelope({ ...x, crypto: { ...x.crypto, cipher: 'bad' } })).toThrow(); expect(() => validateEncryptedEnvelope({ ...x, crypto: { ...x.crypto, salt: 'bad' } })).toThrow() })
})
