import { describe, expect, it } from 'vitest'
import { buildWorkspaceBackup, mergeWorkspace, parseWorkspaceBackup, serializeWorkspaceBackup, WORKSPACE_BACKUP_SCHEMA } from './workspaceBackup'

const universe = ['sano', 'castro', 'fox', 'isrotel']
const store = (initial: Record<string, string> = {}): Storage => { const data = new Map(Object.entries(initial)); return { getItem: key => data.get(key) ?? null, setItem: (key, value) => void data.set(key, value), removeItem: key => void data.delete(key), clear: () => data.clear(), key: index => [...data.keys()][index] ?? null, get length() { return data.size } } as Storage }
const note = (companyId: string, updatedAt: string) => ({ companyId, thesis: 'plain text', catalysts: [], risks: [], questions: [], generalNotes: '', updatedAt })

describe('workspace backup', () => {
  it('exports only the versioned supported envelope', () => { const storage = store({ 'israel-stocks.watchlist.v1': '["SANO","bad"]', 'unrelated': 'secret' }); const backup = buildWorkspaceBackup(storage, universe); expect(backup.schema).toBe(WORKSPACE_BACKUP_SCHEMA); expect(backup.version).toBe(1); expect(backup.appData.watchlist).toEqual(['sano']); expect(serializeWorkspaceBackup(backup)).not.toContain('secret') })
  it('rejects invalid root/version and reports partial invalid records', () => { expect(() => parseWorkspaceBackup('{bad', universe)).toThrow(); expect(() => parseWorkspaceBackup({ schema: WORKSPACE_BACKUP_SCHEMA, version: 2, exportedAt: new Date().toISOString(), appData: {} }, universe)).toThrow(/newer/); const parsed = parseWorkspaceBackup({ schema: WORKSPACE_BACKUP_SCHEMA, version: 1, exportedAt: new Date().toISOString(), appData: { watchlist: ['sano', 'unknown'], savedComparisons: [], researchNotes: [note('sano', 'bad')], reviewState: [] } }, universe); expect(parsed.backup.appData.watchlist).toEqual(['sano']); expect(parsed.invalid).toBe(2) })
  it('merges deterministically and preserves unrelated storage', () => { const storage = store({ unrelated: 'keep' }); const imported = parseWorkspaceBackup({ schema: WORKSPACE_BACKUP_SCHEMA, version: 1, exportedAt: new Date().toISOString(), appData: { watchlist: ['sano'], savedComparisons: [], researchNotes: [note('sano', '2026-01-02T00:00:00.000Z')], reviewState: [{ companyId: 'sano', lastReviewedAt: '2026-01-02T00:00:00.000Z' }] } }, universe).backup; const result = mergeWorkspace(storage, imported, 'merge', universe); expect(result.watchlist).toBe(1); expect(storage.getItem('unrelated')).toBe('keep'); expect(JSON.parse(storage.getItem('israel-stocks.research-notes.v1')!)[0].updatedAt).toContain('2026-01-02') })
  it('replace clears only supported keys', () => { const storage = store({ unrelated: 'keep', 'israel-stocks.watchlist.v1': '["fox"]' }); const imported = parseWorkspaceBackup({ schema: WORKSPACE_BACKUP_SCHEMA, version: 1, exportedAt: new Date().toISOString(), appData: { watchlist: ['sano'], savedComparisons: [], researchNotes: [], reviewState: [] } }, universe).backup; mergeWorkspace(storage, imported, 'replace', universe); expect(storage.getItem('unrelated')).toBe('keep'); expect(storage.getItem('israel-stocks.watchlist.v1')).toBe('["sano"]') })
})
