import type { WorkspaceBackupV1 } from './workspaceBackup'

export const ENCRYPTED_BACKUP_SCHEMA = 'israel-stocks.workspace-backup.encrypted' as const
export const ENCRYPTED_BACKUP_VERSION = 1 as const
export const PBKDF2_ITERATIONS = 310_000
export const MIN_PBKDF2_ITERATIONS = 100_000
export const MAX_PBKDF2_ITERATIONS = 2_000_000
export const SALT_BYTES = 16
export const IV_BYTES = 12
export type EncryptedWorkspaceBackupV1 = { schema: typeof ENCRYPTED_BACKUP_SCHEMA; version: 1; exportedAt: string; crypto: { kdf: 'PBKDF2'; hash: 'SHA-256'; iterations: number; salt: string; cipher: 'AES-GCM'; iv: string }; ciphertext: string }
const bytesToBase64 = (bytes: Uint8Array) => { let binary = ''; bytes.forEach(byte => { binary += String.fromCharCode(byte) }); return btoa(binary) }
const base64ToBytes = (value: unknown) => { if (typeof value !== 'string' || !/^[A-Za-z0-9+/]*={0,2}$/.test(value) || value.length % 4 === 1) throw new Error('Invalid encrypted backup metadata.'); try { const binary = atob(value); if (!binary) throw new Error('Invalid encrypted backup metadata.'); return Uint8Array.from(binary, char => char.charCodeAt(0)) } catch { throw new Error('Invalid encrypted backup metadata.') } }
const cryptoApi = () => { if (typeof crypto === 'undefined' || !crypto.subtle) throw new Error('Encrypted backups are not supported in this browser.'); return crypto }
const deriveKey = async (password: string, salt: Uint8Array, iterations: number) => cryptoApi().subtle.deriveKey({ name: 'PBKDF2', salt: salt as BufferSource, iterations, hash: 'SHA-256' }, await cryptoApi().subtle.importKey('raw', new TextEncoder().encode(password) as BufferSource, 'PBKDF2', false, ['deriveKey']), { name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt'])
export const validateEncryptedEnvelope = (value: unknown): EncryptedWorkspaceBackupV1 => { if (!value || typeof value !== 'object') throw new Error('Encrypted backup is malformed.'); const item = value as any; if (item.schema !== ENCRYPTED_BACKUP_SCHEMA || item.version !== 1) throw new Error(item.version > 1 ? 'Backup version is newer than this app supports.' : 'Unsupported encrypted backup version.'); const meta = item.crypto; if (!meta || meta.kdf !== 'PBKDF2' || meta.hash !== 'SHA-256' || meta.cipher !== 'AES-GCM' || !Number.isInteger(meta.iterations) || meta.iterations < MIN_PBKDF2_ITERATIONS || meta.iterations > MAX_PBKDF2_ITERATIONS || typeof item.exportedAt !== 'string' || Number.isNaN(Date.parse(item.exportedAt))) throw new Error('Encrypted backup metadata is invalid.'); const salt = base64ToBytes(meta.salt); const iv = base64ToBytes(meta.iv); const ciphertext = base64ToBytes(item.ciphertext); if (salt.length !== SALT_BYTES || iv.length !== IV_BYTES || ciphertext.length < 17) throw new Error('Encrypted backup metadata is invalid.'); return item as EncryptedWorkspaceBackupV1 }
export const encryptWorkspaceBackup = async (backup: WorkspaceBackupV1, password: string): Promise<EncryptedWorkspaceBackupV1> => { if (!password) throw new Error('A password is required.'); const api = cryptoApi(); const salt = api.getRandomValues(new Uint8Array(SALT_BYTES)); const iv = api.getRandomValues(new Uint8Array(IV_BYTES)); const key = await deriveKey(password, salt, PBKDF2_ITERATIONS); const ciphertext = await api.subtle.encrypt({ name: 'AES-GCM', iv: iv as BufferSource }, key, new TextEncoder().encode(JSON.stringify(backup)) as BufferSource); return { schema: ENCRYPTED_BACKUP_SCHEMA, version: 1, exportedAt: new Date().toISOString(), crypto: { kdf: 'PBKDF2', hash: 'SHA-256', iterations: PBKDF2_ITERATIONS, salt: bytesToBase64(salt), cipher: 'AES-GCM', iv: bytesToBase64(iv) }, ciphertext: bytesToBase64(new Uint8Array(ciphertext)) } }
export const decryptWorkspaceBackup = async (envelope: EncryptedWorkspaceBackupV1, password: string): Promise<WorkspaceBackupV1> => { try { const valid = validateEncryptedEnvelope(envelope); const key = await deriveKey(password, base64ToBytes(valid.crypto.salt), valid.crypto.iterations); const plain = await cryptoApi().subtle.decrypt({ name: 'AES-GCM', iv: base64ToBytes(valid.crypto.iv) as BufferSource }, key, base64ToBytes(valid.ciphertext) as BufferSource); return JSON.parse(new TextDecoder().decode(plain)) as WorkspaceBackupV1 } catch { throw new Error('Could not decrypt this backup. Check the password or file.') } }
