name = "israel-stocks-api"
main = "worker/src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "israel-stocks-db"
database_id = "d3e038bc-762a-4dc0-89dc-8e4e942335f7"
migrations_dir = "migrations"
