// @ts-nocheck
export type Metric={value:number|null;available:boolean;reason:string|null}
export type AnalyticsRow={periodEnd:string;fiscalYear:number;periodType:string;flowBasis:string|null;sourceIds:string[];revenue:Metric;ebit:Metric;netIncome:Metric;cfo:Metric;capex:Metric;fcf:Metric;grossMargin:Metric;ebitMargin:Metric;netMargin:Metric;fcfMargin:Metric;cashConversion:Metric;revenueGrowth:Metric;ebitGrowth:Metric;netIncomeGrowth:Metric;cfoGrowth:Metric;fcfGrowth:Metric}
const available=(value:number|null,reason:string|null=null):Metric=>({value,available:value!=null&&Number.isFinite(value),reason:value!=null&&Number.isFinite(value)?null:reason})
const n=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:null
const ratio=(a:number|null,b:number|null,reason='MISSING_INPUT')=>a!=null&&b!=null&&b!==0?available(a/b):available(null,reason)
const growth=(a:number|null,b:number|null)=>a!=null&&b!=null&&b!==0?available((a-b)/Math.abs(b)):available(null,b===0?'ZERO_BASE':'MISSING_INPUT')
const cagr=(latest:number|null,oldest:number|null,years:number)=>latest!=null&&oldest!=null&&oldest>0&&latest>=0?available(Math.pow(latest/oldest,1/years)-1):available(null,'SIGN_CHANGE_CAGR_UNDEFINED')
export function annualRows(rows:any[]):any[]{return rows.filter(r=>r.period_type==='ANNUAL').sort((a,b)=>String(a.period_end).localeCompare(String(b.period_end)))}
export function buildAnalytics(rows:any[]){const annual=annualRows(rows);const result:AnalyticsRow[]=annual.map((r,i)=>{const prev=annual[i-1];const revenue=n(r.revenue),ebit=n(r.operating_income),ni=n(r.net_income),cfo=n(r.cash_flow_from_operations),capex=n(r.capex),fcf=cfo!=null&&capex!=null?cfo-capex:null;return {periodEnd:r.period_end,fiscalYear:r.fiscal_year,periodType:r.period_type,flowBasis:r.flow_basis??null,sourceIds:JSON.parse(r.source_ids_json??'[]'),revenue:available(revenue,'MISSING_REVENUE'),ebit:available(ebit,'MISSING_EBIT'),netIncome:available(ni,'MISSING_NET_INCOME'),cfo:available(cfo,'MISSING_CFO'),capex:available(capex,'MISSING_CAPEX'),fcf:available(fcf,'MISSING_FCF_INPUTS'),grossMargin:ratio(n(r.gross_profit),revenue),ebitMargin:ratio(ebit,revenue),netMargin:ratio(ni,revenue),fcfMargin:ratio(fcf,revenue),cashConversion:ratio(cfo,ni),revenueGrowth:growth(revenue,n(prev?.revenue)),ebitGrowth:growth(ebit,n(prev?.operating_income)),netIncomeGrowth:growth(ni,n(prev?.net_income)),cfoGrowth:growth(cfo,n(prev?.cash_flow_from_operations)),fcfGrowth:growth(fcf,prev&&n(prev.cash_flow_from_operations)!=null&&n(prev.capex)!=null?n(prev.cash_flow_from_operations)-n(prev.capex):null)}});const first=annual[0],last=annual.at(-1);return {annual:result,periods:annual.map(r=>({id:r.id,periodEnd:r.period_end,periodType:r.period_type,flowBasis:r.flow_basis??null,sourceIds:JSON.parse(r.source_ids_json??'[]')})),cagr:{revenue:cagr(n(last?.revenue),n(first?.revenue),2),ebit:cagr(n(last?.operating_income),n(first?.operating_income),2),netIncome:cagr(n(last?.net_income),n(first?.net_income),2),fcf:cagr(last&&n(last.cash_flow_from_operations)!=null&&n(last.capex)!=null?n(last.cash_flow_from_operations)-n(last.capex):null,first&&n(first.cash_flow_from_operations)!=null&&n(first.capex)!=null?n(first.cash_flow_from_operations)-n(first.capex):null,2)},roic:available(null,'ROIC_FORMULA_NOT_APPROVED'),signals:signals(result),historicalMarket:{available:false,reason:'HISTORICAL_MARKET_UNAVAILABLE'}}}
export function signals(rows:AnalyticsRow[]){const latest=rows.at(-1),previous=rows.at(-2);const out:any[]=[];if(latest?.ebitMargin.value!=null&&previous?.ebitMargin.value!=null){const delta=latest.ebitMargin.value-previous.ebitMargin.value;if(Math.abs(delta)>=0.01)out.push({code:delta>0?'EBIT_MARGIN_EXPANDED':'EBIT_MARGIN_CONTRACTED',category:'MARGIN',period:latest.periodEnd,explanation:`EBIT margin changed ${(delta*100).toFixed(1)} percentage points versus the prior annual period.`})}if(latest?.fcfMargin.value!=null&&previous?.fcfMargin.value!=null){const delta=latest.fcfMargin.value-previous.fcfMargin.value;if(Math.abs(delta)>=0.01)out.push({code:delta>0?'FCF_MARGIN_EXPANDED':'FCF_MARGIN_CONTRACTED',category:'CASH_FLOW',period:latest.periodEnd,explanation:`FCF margin changed ${(delta*100).toFixed(1)} percentage points versus the prior annual period.`})}return out}
export function peerComparison(items:any[],metric:string){const values=items.map(x=>x[metric]).filter((x:number|null)=>typeof x==='number'&&Number.isFinite(x)) as number[];const sorted=[...values].sort((a,b)=>a-b);const median=sorted.length?sorted[Math.floor((sorted.length-1)/2)]:null;return items.map(x=>({companyId:x.companyId,value:x[metric]??null,available:x[metric]!=null,peerMedian:median,deltaVsPeerMedian:x[metric]!=null&&median!=null?x[metric]-median:null,reason:x[metric]==null?'MISSING_INPUT':null}))}
