import { describe, expect, it } from 'vitest'
import { buildFairValue, buildValuationScore, cashConversionConfidence, classifyEarningsQuality, classifyFcfStability, classifyGrowth, classifyMarginStability, marginOfSafetyScore, normalizeAnnual } from './fairValue'

const rows = (extra: any = {}) => [2023, 2024, 2025].map((year, i) => ({ fiscal_year: year, period_type: 'ANNUAL', operating_income: 100 + i * 10, net_income: 80 + i * 5, cash_flow_from_operations: 130 + i * 5, capex: 30, cash_and_cash_equivalents: 100, short_term_debt: 20, long_term_debt: 30, ...extra }))
const market = { share_price: 10, market_cap: 1000, shares_outstanding: 100000000, as_of: '2026-01-01', provider: 'GLOBES', delay_minutes: 15 }

describe('fair value engine', () => {
  it('scores every margin-of-safety band with explicit boundaries', () => { expect([.45,.35,.25,.15,.05,-.05,-.15,-.25,-.35].map(marginOfSafetyScore)).toEqual([8,7,6,5,4,3,2,1,0]); expect(marginOfSafetyScore(.4)).toBe(8); expect(marginOfSafetyScore(.3)).toBe(7); expect(marginOfSafetyScore(.2)).toBe(6); expect(marginOfSafetyScore(.1)).toBe(5); expect(marginOfSafetyScore(0)).toBe(4); expect(marginOfSafetyScore(-.1)).toBe(3); expect(marginOfSafetyScore(-.2)).toBe(2); expect(marginOfSafetyScore(-.3)).toBe(1) })
  it('scores confidence and dispersion without turning unavailable values into zero', () => { const c = { level: 'MEDIUM', methodCoverage: { availableCount: 2 }, dispersion: { classification: 'LOW', pct: .05 } }; expect(buildValuationScore(.25, 125, 100, c).total).toBe(12); expect(buildValuationScore(null, null, 100, c).total).toBeNull(); expect(buildValuationScore(.25, 125, 100, { ...c, level: 'INSUFFICIENT' }).available).toBe(false) })
  it('normalizes three annual periods by median', () => { const x = normalizeAnnual(rows(), 'operating_income'); expect(x.available).toBe(true); expect(x.median).toBe(110); expect(x.value).toBe(110); expect(x.average).toBe(110) })
  it('keeps missing history unavailable', () => { expect(normalizeAnnual(rows().slice(1), 'operating_income').reason).toBe('INSUFFICIENT_ANNUAL_HISTORY') })
  it('uses annual FY2023-FY2025 only and ignores interim rows', () => { const x = normalizeAnnual([...rows(), { fiscal_year: 2026, period_type: 'QUARTER_ONLY', operating_income: 99999 }, { fiscal_year: 2025, period_type: 'YTD', operating_income: 88888 }], 'operating_income'); expect(x.periods).toEqual(['2023', '2024', '2025']); expect(x.value).toBe(110) })
  it('calculates scenarios, blended values, shares and MOS', () => { const x = buildFairValue('sano', rows(), market, false); expect(x.methods.evEbit.available).toBe(true); expect(x.methods.pe.available).toBe(true); expect(x.methods.fcf.available).toBe(true); expect(x.perShare.base).toBeGreaterThan(0); expect(x.marginOfSafety.mos20).toBe(x.perShare.base! * .8); expect(x.modelVersion).toBe('FV1'); expect(x.valuationScore.modelVersion).toBe('FV1') })
  it('builds deterministic company-specific FV2 from annual evidence and bounded assumptions', () => { const x: any = buildFairValue('sano', rows({ revenue: 1000 }), market, false); expect(x.fv2.modelVersion).toBe('FV2'); expect(x.fv2.profile.business).toBe('CONSUMER_DEFENSIVE_BRANDED'); expect(x.fv2.evidence.annualPeriods).toEqual(['2023', '2024', '2025']); expect(x.fv2.assumptions.evEbit.final).toBeGreaterThanOrEqual(7); expect(x.fv2.assumptions.evEbit.final).toBeLessThanOrEqual(18); expect(x.fv2.perShare.base).toBeGreaterThan(0) })
  it('keeps FV2 FCF unavailable when FV1 FCF is unavailable', () => { const x: any = buildFairValue('rami-levy', rows(), market, true); expect(x.fv2.methods.fcf.available).toBe(false); expect(x.fv2.methods.fcf.reason).toBe('FCF_METHOD_UNAVAILABLE') })
  it('enforces restored FV2 classification thresholds and FCF direction inputs', () => { expect(classifyGrowth(.0799)).toBe('MODERATE'); expect(classifyGrowth(.08)).toBe('STRONG'); expect(classifyGrowth(.0299)).toBe('WEAK'); expect(classifyGrowth(.03)).toBe('MODERATE'); expect(classifyMarginStability(.02)).toBe('STABLE'); expect(classifyMarginStability(.0201)).toBe('MODERATE'); expect(classifyMarginStability(.05)).toBe('MODERATE'); expect(classifyMarginStability(.0501)).toBe('VOLATILE'); expect(classifyFcfStability([10, 12, 11], .18)).toBe('STABLE'); expect(classifyFcfStability([-10, 12, 11], null)).toBe('HIGHLY_VARIABLE') })
  it('applies earnings-quality boundaries and negative-FCF safeguards', () => { expect(classifyEarningsQuality(.8, false, 80)).toBe('EXCELLENT'); expect(classifyEarningsQuality(.7999, false, 80)).toBe('GOOD'); expect(classifyEarningsQuality(.6, false, 60)).toBe('GOOD'); expect(classifyEarningsQuality(.5999, false, 60)).toBe('MODERATE'); expect(classifyEarningsQuality(.4, false, 40)).toBe('MODERATE'); expect(classifyEarningsQuality(.3999, false, 40)).toBe('WEAK'); expect(classifyEarningsQuality(.9, true, 90)).toBe('MODERATE'); expect(classifyEarningsQuality(.5, false, 0)).toBe('WEAK'); expect(classifyEarningsQuality(null, false, null)).toBe('UNAVAILABLE') })
  it('keeps Phase 14 cash conversion unavailable for Rami Levy and does not change FCF yield', () => { const x: any = buildFairValue('rami-levy', rows(), market, true); expect(x.fv2.evidence.earningsQuality.classification).toBe('UNAVAILABLE'); expect(x.fv2.adjustmentRationale.fcfYield.some((item: any) => item.code.startsWith('EARNINGS_QUALITY'))).toBe(false) })
  it('assigns deterministic confidence states without changing quality', () => { const base: any = { normalizedFCF: 100, normalizedNetIncome: 100, fcfEvidenceComplete: true, leaseEvidenceComplete: true, capexInterpretationStatus: 'CLEAR' }; expect(cashConversionConfidence({ ...base, workingCapitalCoverage: 'COMPLETE' }).level).toBe('HIGH'); expect(cashConversionConfidence({ ...base, workingCapitalCoverage: 'PARTIAL' }).level).toBe('MEDIUM'); expect(cashConversionConfidence({ ...base, workingCapitalCoverage: 'UNAVAILABLE', capexInterpretationStatus: 'UNRESOLVED' }).level).toBe('LOW'); expect(cashConversionConfidence({ ...base, normalizedFCF: null, workingCapitalCoverage: 'COMPLETE' }).level).toBe('UNAVAILABLE') })
  it('requires complete retailer lease evidence for HIGH and preserves non-retailer N/A', () => { const base: any = { normalizedFCF: 100, normalizedNetIncome: 100, fcfEvidenceComplete: true, workingCapitalCoverage: 'COMPLETE', capexInterpretationStatus: 'CLEAR' }; expect(cashConversionConfidence({ ...base, leaseEvidenceComplete: false }).level).toBe('LOW'); expect(cashConversionConfidence({ ...base, leaseEvidenceComplete: 'NOT_APPLICABLE' }).level).toBe('HIGH'); const x: any = buildFairValue('rami-levy', rows(), market, true); expect(x.fv2.evidence.earningsQuality.cashConversionConfidence.level).toBe('UNAVAILABLE') })
  it('does not infer retailer lease-adjusted FCF', () => { const x = buildFairValue('rami-levy', rows(), market, true); expect(x.methods.fcf.available).toBe(false); expect((x.methods.fcf as any).reason).toBe('MISSING_RETAIL_LEASE_CASH_PAYMENTS') })
  it('uses retailer adjusted FCF only with three explicit lease totals', () => { const x = buildFairValue('shufersal', rows({ total_lease_cash_payments: 10 }), market, true); expect(x.normalization.fcf.value).toBe(95); expect(x.methods.fcf.available).toBe(true); expect(x.confidence.valuationBasis).toBe('EARNINGS_AND_CASH_FLOW') })
  it('keeps non-positive FCF unavailable', () => { const x = buildFairValue('sano', rows({ capex: 200 }), market, false); expect(x.methods.fcf.available).toBe(false) })
  it('keeps a positive normalized FCF available when one annual FCF is negative', () => { const y = buildFairValue('neto-malinda', [...rows({ cash_flow_from_operations: 150, capex: 50 }).slice(0, 2), { ...rows()[2], cash_flow_from_operations: -60, capex: 40 }], market, false); expect(y.normalization.fcf.value).toBe(100); expect(y.methods.fcf.available).toBe(true) })
  it('renormalizes weights when a method is missing', () => { const x = buildFairValue('shufersal', rows(), market, true); expect(x.blended.effectiveWeights.fcf).toBe(0); expect(x.blended.effectiveWeights.evEbit + x.blended.effectiveWeights.pe).toBeCloseTo(1) })
  it('reports two-method earnings-only confidence and excludes FCF from dispersion', () => { const x = buildFairValue('sano', rows(), market, true); expect(x.confidence.methodCoverage).toMatchObject({ availableCount: 2, totalCount: 3, availableMethods: ['EV_EBIT', 'PE'] }); expect(x.confidence.valuationBasis).toBe('EARNINGS_ONLY'); expect(x.confidence.level).toBe('MEDIUM'); expect(x.confidence.dispersion.availableBaseValues).not.toHaveProperty('FCF') })
  it('reports low confidence for very high method dispersion', () => { const x = buildFairValue('sano', rows({ net_income: 1 }), market, true); expect(x.confidence.dispersion.classification).toBe('VERY_HIGH'); expect(x.confidence.level).toBe('LOW') })
  it('reports insufficient confidence when fewer than two methods are available', () => { const x = buildFairValue('sano', rows({ net_income: null, cash_flow_from_operations: null, capex: null, cash_and_cash_equivalents: null }), market, false); expect(x.confidence.methodCoverage.availableCount).toBe(0); expect(x.confidence.level).toBe('INSUFFICIENT') })
})
