import { MayaReportDiscoveryProvider } from './maya'
import { GLOBES_MAP, fetchGlobesSnapshot } from './market/globes-provider'
export interface Env { DB:D1Database; ALLOWED_ORIGINS?:string }
interface D1Database { prepare(sql:string):{bind(...v:unknown[]):{all<T>():Promise<{results:T[]}>;first<T>():Promise<T|null>;run():Promise<unknown>}} }
const reply=(b:unknown,s=200,o='*')=>new Response(JSON.stringify(b),{status:s,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':o}})
const allowed=(r:Request,e:Env)=>e.ALLOWED_ORIGINS?.split(',').includes(r.headers.get('origin')??'')?r.headers.get('origin')!:'*'
const map=(r:any)=>({...r,fiscalQuarter:r.fiscal_quarter,periodType:r.period_type,periodEnd:r.period_end,flowBasis:r.flow_basis,sourceIds:JSON.parse(r.source_ids_json??'[]'),financials:r})
async function market(db:D1Database,id:string){const m=await db.prepare('SELECT * FROM market_snapshots WHERE company_id=? ORDER BY COALESCE(as_of,snapshot_date) DESC LIMIT 1').bind(id).first<any>();if(!m)return null;const f=await db.prepare("SELECT s.net_income,s.operating_income,s.ebitda_reported,s.cash_and_cash_equivalents,s.short_term_debt,s.long_term_debt,p.period_end,p.period_type FROM financial_periods p JOIN financial_statements s ON s.period_id=p.id WHERE p.company_id=? AND p.period_type='ANNUAL' ORDER BY p.period_end DESC LIMIT 1").bind(id).first<any>();const debt=f?.short_term_debt!=null&&f?.long_term_debt!=null?f.short_term_debt+f.long_term_debt:null;const nd=debt!=null&&f?.cash_and_cash_equivalents!=null?debt-f.cash_and_cash_equivalents:null;const ev=nd!=null?m.market_cap+nd:null;const reasons:string[]=[];if(!f)reasons.push('TTM_NOT_AVAILABLE','MISSING_NET_INCOME','MISSING_EBIT','MISSING_EBITDA');if(nd==null)reasons.push('MISSING_NET_DEBT_INPUTS');return {...m,day_change:m.day_change==null?null:m.day_change/100,valuation:{basis:f?{earnings:'LATEST_ANNUAL',ebitda:'LATEST_ANNUAL',ebit:'LATEST_ANNUAL',fcf:'UNAVAILABLE',balanceSheet:f.period_end}:null,periodEnd:f?.period_end??null,enterpriseValueIlsMillions:ev,pe:f?.net_income>0?m.market_cap/f.net_income:null,evEbit:f?.operating_income>0&&ev!=null?ev/f.operating_income:null,evEbitda:f?.ebitda_reported>0&&ev!=null?ev/f.ebitda_reported:null,priceToFcf:null,fcfYield:null,netDebtToMarketCap:nd!=null?nd/m.market_cap:null,netCashToMarketCap:nd!=null&&nd<0?-nd/m.market_cap:null,unavailableReasons:reasons}}}
async function refresh(db:D1Database){for(const id of Object.keys(GLOBES_MAP))try{const s=await fetchGlobesSnapshot(id);await db.prepare(`INSERT OR REPLACE INTO market_snapshots(id,company_id,provider,provider_instrument_id,security_id,exchange,currency,snapshot_date,as_of,fetched_at,share_price,previous_close,day_change,day_change_pct,market_cap,shares_outstanding,source_id,data_status,validation_status,raw_price,raw_price_unit,delay_minutes,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,datetime('now'))`).bind(`globes-${id}-${s.asOf}`,id,s.provider,s.providerInstrumentId,s.securityId,s.exchange,s.currency,s.asOf,s.asOf,s.fetchedAt,s.priceIls,s.previousCloseIls,s.dayChange==null?null:s.dayChange/100,s.dayChangePct,s.marketCapIlsMillions,s.sharesOutstanding,s.sourceRef,'VERIFIED','PASS',s.rawPrice,s.rawPriceUnit,s.delayMinutes).run()}catch(e){console.error('Globes refresh failed',id,e)}}
export default {async fetch(req:Request,env:Env){const o=allowed(req,env);const p=new URL(req.url).pathname.split('/').filter(Boolean);try{if(p[1]!=='companies')return reply({error:{code:'NOT_FOUND'}},404,o);const id=p[2];if(!id)return reply({companies:(await env.DB.prepare('SELECT * FROM companies WHERE is_active=1').bind().all()).results},200,o);if(p.length===3)return reply({company:await env.DB.prepare('SELECT * FROM companies WHERE id=? AND is_active=1').bind(id).first()},200,o);if(p[3]==='market'&&p[4]==='latest')return reply({market:await market(env.DB,id)},200,o);if(p[3]==='financials'){const rows=await env.DB.prepare('SELECT p.*,s.* FROM financial_periods p LEFT JOIN financial_statements s ON s.period_id=p.id WHERE p.company_id=? ORDER BY p.period_end,p.period_type,p.id').bind(id).all<any>();const seen=new Set();return reply({financials:rows.results.filter(r=>{const k=`${r.period_end}|${r.period_type}|${r.flow_basis??''}`;if(seen.has(k))return false;seen.add(k);return true}).map(map)},200,o)}if(p[3]==='sources')return reply({sources:(await env.DB.prepare('SELECT * FROM financial_sources WHERE company_id=?').bind(id).all()).results},200,o);if(p[3]==='validation')return reply({validation:(await env.DB.prepare('SELECT * FROM validation_results WHERE company_id=?').bind(id).all()).results},200,o);return reply({error:{code:'NOT_FOUND'}},404,o)}catch(e){return reply({error:{code:'DATABASE_ERROR'}},500,o)}},async scheduled(e:ScheduledController,env:Env){if(e.cron!=='0 6 * * *')await refresh(env.DB)}}
interface ScheduledController { cron:string }
