export interface MayaReport { provider:'MAYA'; companyId:string; externalCompanyId:string; externalReportId:string; title:string; reportType:'Q1'|'Q2'|'Q3'|'ANNUAL'|'UNKNOWN'; fiscalYear:number|null; periodEnd:string|null; publishedAt:string|null; reportPageUrl:string; pdfUrl:string|null; htmlUrl:string|null; xbrlUrl:string|null; discoveredAt:string }
export interface ReportDiscoveryProvider { discoverFinancialReports(company:{id:string;mayaCompanyId?:number|null}):Promise<MayaReport[]> }
export class MayaUnexpectedPayloadError extends Error { constructor(public details:{status:number;contentType:string;endpoint:string;attempt:number;companyId:number;page:number;snippet:string}){super(`MAYA_UNEXPECTED_PAYLOAD ${details.endpoint} status=${details.status} attempt=${details.attempt}`)} }
async function mayaJson(url:string,init:RequestInit,companyId:number,page:number){for(let attempt=1;attempt<=3;attempt++){try{const r=await fetch(url,init);const contentType=r.headers.get('content-type')??'';const text=await r.text();let payload:any;try{payload=JSON.parse(text)}catch{payload=null}if(r.ok&&Array.isArray(payload))return payload;if(r.status>=400&&r.status<500&&r.status!==429)throw new MayaUnexpectedPayloadError({status:r.status,contentType,endpoint:url,attempt,companyId,page,snippet:text.slice(0,240)});if(attempt===3)throw new MayaUnexpectedPayloadError({status:r.status,contentType,endpoint:url,attempt,companyId,page,snippet:text.slice(0,240)})}catch(e){if(e instanceof MayaUnexpectedPayloadError&&attempt===3)throw e;if(attempt===3)throw e}await new Promise(x=>setTimeout(x,250*2**(attempt-1)))}throw new Error('unreachable')}
export const classifyMayaReport=(title:string):MayaReport['reportType']=>(/רבעון ראשון|רבעון 1|Q1/i.test(title)?'Q1':/רבעון שני|רבעון 2|Q2/i.test(title)?'Q2':/רבעון שלישי|רבעון 3|Q3/i.test(title)?'Q3':/שנתי|תקופתי|annual/i.test(title)?'ANNUAL':'UNKNOWN')
export const parseMayaReportUrl=(url:string)=>new URL(url).pathname.match(/companies\/(\d+)/)?.[1]??null
const attachmentUrl=(path:string|null)=>path?(path.startsWith('http')?path:`https://mayafiles.tase.co.il/${path}`):null
export function resolveMayaReport(raw:any,companyId='sano'):MayaReport { const title=String(raw.title??''),year=Number(raw.publishDate?.slice(0,4))||null,attachments=raw.attachments??[];const pick=(type:string)=>attachmentUrl(attachments.find((a:any)=>String(a.fileType).toLowerCase()===type)?.url??null);return {provider:'MAYA',companyId,externalCompanyId:String(raw.reporterId??raw.companyId??''),externalReportId:String(raw.id),title,reportType:classifyMayaReport(title),fiscalYear:year,periodEnd:year?`${year}-${/רבעון שני|רבעון 2|Q2/i.test(title)?'06':/רבעון שלישי|רבעון 3|Q3/i.test(title)?'09':'12'}-30`:null,publishedAt:raw.publishDate??null,reportPageUrl:`https://maya.tase.co.il/he/reports/companies/${raw.id}`,pdfUrl:pick('pdf1'),htmlUrl:pick('htm'),xbrlUrl:pick('xbrl'),discoveredAt:new Date().toISOString()} }
export class MayaReportDiscoveryProvider implements ReportDiscoveryProvider { constructor(private readonly fetcher:typeof fetch=fetch){} async discoverFinancialReports(company:{id:string;mayaCompanyId?:number|null}){if(!company.mayaCompanyId)return[];const list=await mayaJson('https://maya.tase.co.il/api/v1/reports/finance',{method:'POST',headers:{'content-type':'application/json','user-agent':'Mozilla/5.0'},body:JSON.stringify({pageSize:30,pageNumber:1,companyId:company.mayaCompanyId})},company.mayaCompanyId,1);const reports:MayaReport[]=[];for(const item of list){const detail=await this.fetcher(`https://maya.tase.co.il/api/v1/reports/${item.id}`,{headers:{'user-agent':'Mozilla/5.0'}});if(detail.ok){const report=resolveMayaReport(await detail.json(),company.id);if(report.reportType!=='UNKNOWN')reports.push(report)}}return [...new Map(reports.map(x=>[x.externalReportId,x])).values()]} }
