export interface MayaReport { provider:'MAYA'; companyId:string; externalCompanyId:string; externalReportId:string; title:string; reportType:'Q1'|'Q2'|'Q3'|'ANNUAL'|'UNKNOWN'; fiscalYear:number|null; periodEnd:string|null; publishedAt:string|null; reportPageUrl:string; pdfUrl:string|null; htmlUrl:string|null; xbrlUrl:string|null; discoveredAt:string }
export interface ReportDiscoveryProvider { discoverFinancialReports(company:{id:string;mayaCompanyId?:number|null}):Promise<MayaReport[]> }
export const MAYA_FINANCIAL_EVENT_IDS=[101,103,104,105,106,102] as const
export class MayaUnexpectedPayloadError extends Error { constructor(public details:any){super(`MAYA_UNEXPECTED_PAYLOAD ${details.endpoint} status=${details.status} attempt=${details.attempt}`)} }
async function json(url:string,init:RequestInit){for(let attempt=1;attempt<=3;attempt++){const r=await fetch(url,init),text=await r.text();let data:any;try{data=JSON.parse(text)}catch{data=null}if(r.ok&&Array.isArray(data))return data;if(attempt===3)throw new MayaUnexpectedPayloadError({endpoint:url,status:r.status,attempt,snippet:text.slice(0,240)});await new Promise(x=>setTimeout(x,250*2**(attempt-1)))}throw Error('unreachable')}
export const classifyMayaReport=(title:string):MayaReport['reportType']=>(/רבעון ראשון|רבעון 1|Q1/i.test(title)?'Q1':/רבעון שני|רבעון 2|Q2|חצי שנתי/i.test(title)?'Q2':/רבעון שלישי|רבעון 3|Q3/i.test(title)?'Q3':/שנתי|שנתית|תקופתית|annual/i.test(title)?'ANNUAL':'UNKNOWN')
const attachmentUrl=(p:string|null)=>p?(p.startsWith('http')?p:`https://mayafiles.tase.co.il/${p}`):null
export function resolveMayaReport(raw:any,companyId='sano'):MayaReport {const title=String(raw.title??''),year=Number(title.match(/20\d{2}/)?.[0]??raw.publishDate?.slice(0,4))||null,a=raw.attachments??[],pick=(t:string)=>attachmentUrl(a.find((x:any)=>String(x.fileType).toLowerCase()===t)?.url??null),type=classifyMayaReport(title);return {provider:'MAYA',companyId,externalCompanyId:String(raw.reporterId??raw.companyId??''),externalReportId:String(raw.id),title,reportType:type,fiscalYear:year,periodEnd:year?`${year}-${type==='Q1'?'03':type==='Q2'?'06':type==='Q3'?'09':'12'}-${type==='ANNUAL'?'31':'30'}`:null,publishedAt:raw.publishDate??null,reportPageUrl:`https://maya.tase.co.il/he/reports/companies/${raw.id}`,pdfUrl:pick('pdf1'),htmlUrl:pick('htm'),xbrlUrl:pick('xbrl'),discoveredAt:new Date().toISOString()}}
export function buildHistoricalRequest(companyId:number,fromDate='2023-01-01',toDate=new Date().toISOString().slice(0,10),pageNumber=1){const [fromYear,toYear]=[Number(fromDate.slice(0,4)),Number(toDate.slice(0,4))];return {url:'https://maya.tase.co.il/api/v1/reports/finance',method:'POST',body:{pageSize:30,pageNumber,fromYear,toYear,period:5,by:'company',companyId,eventsIds:[...MAYA_FINANCIAL_EVENT_IDS]}}}
export async function discoverHistoricalFinancialReports(company:{id:string;mayaCompanyId:number},fromDate='2023-01-01',toDate=new Date().toISOString().slice(0,10)){const reports:MayaReport[]=[];for(let page=1;page<=20;page++){const q=buildHistoricalRequest(company.mayaCompanyId,fromDate,toDate,page),items=await json(q.url,{method:q.method,headers:{'content-type':'application/json','user-agent':'Mozilla/5.0'},body:JSON.stringify(q.body)});for(const item of items){const d=await fetch(`https://maya.tase.co.il/api/v1/reports/${item.id}`,{headers:{'user-agent':'Mozilla/5.0'}});if(d.ok){const r=resolveMayaReport(await d.json(),company.id);if(r.reportType!=='UNKNOWN')reports.push(r)}}if(items.length<30)break}return [...new Map(reports.map(r=>[r.externalReportId,r])).values()]}
export class MayaReportDiscoveryProvider implements ReportDiscoveryProvider { async discoverFinancialReports(company:{id:string;mayaCompanyId?:number|null}){return company.mayaCompanyId?discoverHistoricalFinancialReports({id:company.id,mayaCompanyId:company.mayaCompanyId}):[]}}
