export type PdfTextItem={pageNumber:number;text:string;x:number;y:number;width:number;height:number}
export type PdfLine={pageNumber:number;text:string;items:PdfTextItem[];y:number}
export function groupPdfLines(items:PdfTextItem[],tolerance=2):PdfLine[]{const out:PdfLine[]=[];for(const item of items){let line=out.find(x=>x.pageNumber===item.pageNumber&&Math.abs(x.y-item.y)<=tolerance);if(!line){line={pageNumber:item.pageNumber,text:'',items:[],y:item.y};out.push(line)}line.items.push(item);line.items.sort((a,b)=>a.x-b.x);line.text=line.items.map(x=>x.text).join(' ').replace(/\s+/g,' ').trim()}return out.sort((a,b)=>a.pageNumber-b.pageNumber||b.y-a.y)}
export type PdfNumberToken=PdfTextItem&{value:number;raw:string}
export type PdfColumnCluster={center:number;min:number;max:number;count:number;kind:'label'|'note'|'numeric'}
export type PdfYearHeader={year:number;xCenter:number;headerY:number;rawHeaderText:string}
export type PdfGeometryRow={label:string;labelFragments:string[];y:number;numericTokens:PdfNumberToken[];values:Record<number,number|null>;ambiguous:boolean}
export type PdfGeometryTable={pageNumber:number;section:string;scope:'CONSOLIDATED'|'SEPARATE'|'UNKNOWN';unit:string|null;headers:PdfYearHeader[];columns:PdfColumnCluster[];rows:PdfGeometryRow[];evidence:string[]}
const numericPattern=/^\(?[-−]?(?:\d{1,3}(?:,\d{3})+|\d+(?:\.\d+)?)(?:[a-z%])?\)?$/i
export function adaptivePdfLines(items:PdfTextItem[],factor=0.35){const heights=items.map(x=>x.height).filter(x=>x>0);const median=heights.sort((a,b)=>a-b)[Math.floor(heights.length/2)]||8;return groupPdfLines(items,Math.max(1.5,Math.min(5,median*factor)))}
export function parsePdfNumber(raw:string){const s=raw.trim().replace(/−/g,'-');if(!numericPattern.test(s))return null;const negative=/^\(.*\)$/.test(s);const clean=s.replace(/[(),]/g,'').replace(/%$/,'');const n=Number(clean);return Number.isFinite(n)?(negative?-Math.abs(n):n):null}
export function numericTokens(line:PdfLine):PdfNumberToken[]{return line.items.flatMap(item=>{const value=parsePdfNumber(item.text);return value==null?[]:[{...item,value,raw:item.text}]})}
export function clusterNumericColumns(lines:PdfLine[],minCount=3):PdfColumnCluster[]{const xs=lines.flatMap(line=>numericTokens(line)).map(x=>x.x+x.width/2).sort((a,b)=>a-b);const clusters:PdfColumnCluster[]=[];for(const x of xs){const existing=clusters.find(c=>Math.abs(c.center-x)<=18);if(existing){existing.center=(existing.center*existing.count+x)/(existing.count+1);existing.min=Math.min(existing.min,x);existing.max=Math.max(existing.max,x);existing.count++}else clusters.push({center:x,min:x,max:x,count:1,kind:'numeric'})}return clusters.filter(x=>x.count>=minCount).sort((a,b)=>a.center-b.center)}
export function detectYearHeaders(lines:PdfLine[],years=[2025,2024,2023]):PdfYearHeader[]{const out:PdfYearHeader[]=[];for(const line of lines){for(const year of years){for(const item of line.items.filter(x=>new RegExp(`(^|\\D)${year}($|\\D)`).test(x.text))){const xCenter=item.x+item.width/2;if(!out.some(x=>x.year===year&&Math.abs(x.headerY-line.y)<4&&Math.abs(x.xCenter-xCenter)<8))out.push({year,xCenter,headerY:line.y,rawHeaderText:line.text})}}}return out.sort((a,b)=>a.headerY-b.headerY||a.xCenter-b.xCenter)}
export function bindUnit(lines:PdfLine[],pageNumber:number){const text=lines.filter(x=>x.pageNumber===pageNumber).map(x=>x.text).join(' ');return resolvePdfUnit(text)}
export function detectScope(text:string):'CONSOLIDATED'|'SEPARATE'|'UNKNOWN'{if(/consolidated|מאוחד|מאוחדים|מאוחדות|×ž××•×—×“|×ž××•×—×“×™×|×“×•×—×•×ª ×ž××•×—×“×™×/i.test(text))return 'CONSOLIDATED';if(/separate|נפרד|נפרדים|נפרדות|× ×¤×¨×“×™×|×“×•×—×•×ª × ×¤×¨×“×™×/i.test(text))return 'SEPARATE';return 'UNKNOWN'}
export function reconstructGeometryTable(pageNumber:number,lines:PdfLine[],section='OTHER'):PdfGeometryTable{const headers=detectYearHeaders(lines);const columns=clusterNumericColumns(lines,2);const rows:PdfGeometryRow[]=[];for(const line of lines){const nums=numericTokens(line);if(!nums.length)continue;const label=line.items.filter(x=>parsePdfNumber(x.text)==null).map(x=>x.text).join(' ').trim();if(!label)continue;const values:Record<number,number|null>={};let ambiguous=nums.some(token=>/^\d$/.test(token.raw.trim())&&nums.length>2);for(const token of nums){const distances=headers.map(h=>({year:h.year,d:Math.abs(token.x+token.width/2-h.xCenter)})).sort((a,b)=>a.d-b.d);if(!distances.length||distances[0].d>45||(distances[1]&&distances[1].d-distances[0].d<6)){ambiguous=true;continue}values[distances[0].year]=token.value}rows.push({label,labelFragments:[label],y:line.y,numericTokens:nums,values,ambiguous})}return {pageNumber,section,scope:detectScope(lines.map(x=>x.text).join(' ')),unit:bindUnit(lines,pageNumber),headers,columns,rows,evidence:headers.map(x=>`header ${x.year} x=${x.xCenter.toFixed(2)} y=${x.headerY.toFixed(2)})`)} }
export function reconstructWrappedLabels(lines:PdfLine[],labelX:number):PdfLine[]{const out:PdfLine[]=[];for(const line of lines){const nums=numericTokens(line);if(nums.length||!line.items.length){out.push(line);continue}const x=line.items[0].x;if(Math.abs(x-labelX)<45&&out.length&&out[out.length-1].items.every(i=>parsePdfNumber(i.text)==null)){out[out.length-1]={...out[out.length-1],text:`${out[out.length-1].text} ${line.text}`.trim(),items:[...out[out.length-1].items,...line.items]}}else out.push(line)}return out}
export function resolvePdfYearColumn(headers:string[],year:number){const found=headers.map((text,index)=>({text,index})).filter(x=>new RegExp(`(^|\\D)${year}($|\\D)`).test(x.text));return found.length===1?found[0]:null}
export function resolvePdfUnit(text:string){const s=text.toLocaleLowerCase();if(/אלפי|thousands|000/.test(s))return 'THOUSANDS_ILS';if(/מיליוני|millions/.test(s))return 'MILLIONS_ILS';if(/שח|nis|₪/.test(s))return 'ILS';return null}
export function rtlAwareTokens(items:PdfTextItem[]){return [...items].sort((a,b)=>a.y-b.y||a.x-b.x).map(x=>x.text)}
export function explicitTotalLeaseCash(label:string){return /total.*lease.*cash|lease.*payments.*total|סך.*תשלומי.*חכיר/i.test(label)}
export function canDeriveAdjustedFcf(cfo:number|null,capex:number|null,totalLeaseCash:number|null){return cfo!=null&&capex!=null&&totalLeaseCash!=null}
