export type PdfTextItem={pageNumber:number;text:string;x:number;y:number;width:number;height:number}
export type PdfLine={pageNumber:number;text:string;items:PdfTextItem[];y:number}
export function groupPdfLines(items:PdfTextItem[],tolerance=2):PdfLine[]{const out:PdfLine[]=[];for(const item of items){let line=out.find(x=>x.pageNumber===item.pageNumber&&Math.abs(x.y-item.y)<=tolerance);if(!line){line={pageNumber:item.pageNumber,text:'',items:[],y:item.y};out.push(line)}line.items.push(item);line.items.sort((a,b)=>a.x-b.x);line.text=line.items.map(x=>x.text).join(' ').replace(/\s+/g,' ').trim()}return out.sort((a,b)=>a.pageNumber-b.pageNumber||b.y-a.y)}
export type PdfNumberToken=PdfTextItem&{value:number;raw:string}
export type PdfColumnCluster={center:number;min:number;max:number;count:number;kind:'label'|'note'|'numeric'}
export type PdfYearHeader={year:number;xCenter:number;headerY:number;rawHeaderText:string}
export type PdfGeometryRow={label:string;labelFragments:string[];y:number;numericTokens:PdfNumberToken[];values:Record<number,number|null>;ambiguous:boolean}
export type PdfGeometryTable={pageNumber:number;section:string;scope:'CONSOLIDATED'|'SEPARATE'|'UNKNOWN';unit:string|null;headers:PdfYearHeader[];columns:PdfColumnCluster[];rows:PdfGeometryRow[];evidence:string[]}
export type StatementType='BALANCE_SHEET'|'CASH_FLOW'|'INCOME_STATEMENT'|'CHANGES_IN_EQUITY'|'BORROWINGS_NOTE'|'LEASE_NOTE'|'OTHER'
export type PdfPageStructure={pageNumber:number;topHeadingCandidates:string[];bottomHeadingCandidates:string[];sectionKeywords:string[];consolidatedKeywords:string[];separateCompanyKeywords:string[];noteNumberCandidates:number[];tocReferences:{title:string;declaredPage:number}[];financialStatementTypeCandidate:StatementType;scopeCandidate:'CONSOLIDATED'|'SEPARATE'|'SUBSIDIARY'|'SEGMENT'|'NOTE_DETAIL'|'UNKNOWN';confidence:'HIGH'|'MEDIUM'|'LOW'}
export type StatementRange={type:StatementType;scope:'CONSOLIDATED'|'SEPARATE'|'UNKNOWN';startPage:number;endPage:number;heading:string;tocEntry?:string;confidence:'HIGH'|'MEDIUM'|'LOW'}
export type PdfHeading={pageNumber:number;text:string;xMin:number;xMax:number;y:number;fontSize:number;tokenCount:number;centeredness:number;sectionType:StatementType;scope:'CONSOLIDATED'|'SEPARATE'|'UNKNOWN';strength:number}
export type PdfHeadingRegion={pageNumber:number;heading:PdfHeading;startY:number;endY:number;lines:PdfLine[];unit:string|null;headers:PdfYearHeader[];numericClusters:PdfColumnCluster[];rows:PdfGeometryRow[];tableLike:boolean;confidence:'HIGH'|'MEDIUM'|'LOW';rejectionReasons:string[]}
const consolidatedPattern=/consolidated|מאוחד|מאוחדים|מאוחדות|×ž××•×—×“|×ž××•×—×“×™×/i
const separatePattern=/separate|נפרד|נפרדים|× ×¤×¨×“/i
export function detectStatementType(text:string):StatementType{if(/cash flow|תזרימי המזומנים|×ª×–×¨×™×ž×™ ×”×ž×–×•×ž× ×™×/i.test(text))return 'CASH_FLOW';if(/balance sheet|financial position|המצב הכספי|המאזן|×”×ž×¦×‘ ×”×›×¡×¤×™|×”×ž××–×Ÿ/i.test(text))return 'BALANCE_SHEET';if(/income statement|profit and loss|רווח או הפסד|×¨×•×•×— ××• ×”×¤×¡×“/i.test(text))return 'INCOME_STATEMENT';if(/changes in equity|השינויים בהון|×”×©×™× ×•×™×™× ×‘×”×•×Ÿ/i.test(text))return 'CHANGES_IN_EQUITY';if(/borrow|debt|הלוואות|אגרות חוב|×”×œ×•×•××•×ª|××’×¨×•×ª ×—×•×‘/i.test(text))return 'BORROWINGS_NOTE';if(/lease|חכירה|×—×›×™×¨/i.test(text))return 'LEASE_NOTE';return 'OTHER'}
export function classifyScope(text:string):PdfPageStructure['scopeCandidate']{if(separatePattern.test(text)&&!consolidatedPattern.test(text))return 'SEPARATE';if(consolidatedPattern.test(text))return 'CONSOLIDATED';if(/subsidiary|חברה בת|×—×‘×¨×” ×‘×ª/i.test(text))return 'SUBSIDIARY';if(/segment|מגזר|×ž×’×–×¨/i.test(text))return 'SEGMENT';if(/note|באור|ביאור|×‘×™××•×¨/i.test(text))return 'NOTE_DETAIL';return 'UNKNOWN'}
export function buildPageStructure(pageNumber:number,lines:PdfLine[]):PdfPageStructure{const text=lines.map(x=>x.text).join(' ');const top=lines.filter(x=>x.y>Math.max(...lines.map(y=>y.y),0)-90).map(x=>x.text);const bottom=lines.filter(x=>x.y<Math.min(...lines.map(y=>y.y),0)+90).map(x=>x.text);const type=detectStatementType(text);const scope=classifyScope(text);const noteNumbers=lines.flatMap(numericTokens).filter(x=>x.value>=1&&x.value<=99).map(x=>x.value);return {pageNumber,topHeadingCandidates:top,bottomHeadingCandidates:bottom,sectionKeywords:[type],consolidatedKeywords:consolidatedPattern.test(text)?[text]:[],separateCompanyKeywords:separatePattern.test(text)?[text]:[],noteNumberCandidates:[...new Set(noteNumbers)],tocReferences:[],financialStatementTypeCandidate:type,scopeCandidate:scope,confidence:type!=='OTHER'&&scope==='CONSOLIDATED'?'HIGH':type!=='OTHER'?'MEDIUM':'LOW'}}
export function detectTocReferences(lines:PdfLine[]){return lines.flatMap(line=>{const text=line.text;if(!/contents|תוכן|×ª×•×›×Ÿ/i.test(text)&&!/(financial statements|הדוחות הכספיים|×“×•×—×•×ª ×›×¡×¤×™×™×)/i.test(text))return [];const years=[...text.matchAll(/\b(\d{1,3})\b/g)].map(x=>Number(x[1])).filter(x=>x>1&&x<500);return years.length?[{title:text,declaredPage:years[years.length-1]}]:[]})}
export function constructStatementRanges(structures:PdfPageStructure[]):StatementRange[]{const ranges:StatementRange[]=[];for(const page of structures){if(page.scopeCandidate!=='CONSOLIDATED')continue;const type=page.financialStatementTypeCandidate;if(!['BALANCE_SHEET','CASH_FLOW','INCOME_STATEMENT','CHANGES_IN_EQUITY'].includes(type))continue;const previous=ranges[ranges.length-1];if(previous&&previous.type===type&&page.pageNumber===previous.endPage+1){previous.endPage=page.pageNumber;continue}ranges.push({type,scope:'CONSOLIDATED',startPage:page.pageNumber,endPage:page.pageNumber,heading:page.topHeadingCandidates[0]??'',confidence:page.confidence})}return ranges}
export function detectStrongHeadings(lines:PdfLine[]):PdfHeading[]{return lines.flatMap(line=>{const text=line.text;const sectionType=detectStatementType(text);const scope=classifyScope(text);const words=line.items.filter(x=>parsePdfNumber(x.text)==null);const numeric=numericTokens(line).length;const phrase=sectionType!=='OTHER'&&scope==='CONSOLIDATED';if(!phrase||numeric>2)return [];const xMin=Math.min(...line.items.map(x=>x.x));const xMax=Math.max(...line.items.map(x=>x.x+x.width));const fontSize=line.items.reduce((s,x)=>s+x.height,0)/(line.items.length||1);const center=(xMin+xMax)/2;const pageCenter=300;const centeredness=Math.max(0,1-Math.abs(center-pageCenter)/pageCenter);const strength=(phrase?5:0)+(centeredness>0.65?2:0)+(fontSize>=11?2:0)+(words.length<=18?1:0);return [{pageNumber:line.pageNumber,text,xMin,xMax,y:line.y,fontSize,tokenCount:line.items.length,centeredness,sectionType,scope,strength}]})}
export function regionForHeading(heading:PdfHeading,lines:PdfLine[],nextHeadingY?:number):PdfHeadingRegion{const pageLines=lines.filter(x=>x.pageNumber===heading.pageNumber);const below=pageLines.filter(x=>x.y<heading.y&&(nextHeadingY==null||x.y>nextHeadingY));const endY=below.length?Math.min(...below.map(x=>x.y)):heading.y;const headers=detectYearHeaders(below);const clusters=clusterNumericColumns(below,2);const table=reconstructGeometryTable(heading.pageNumber,below,heading.sectionType);const prose=below.filter(x=>x.items.length>12&&numericTokens(x).length===0).length;const rejectionReasons:string[]=[];if(!headers.length)rejectionReasons.push('NO_LOCAL_YEAR_HEADERS');if(clusters.length<2)rejectionReasons.push('NO_REPEATED_NUMERIC_COLUMNS');if(table.rows.filter(x=>!x.ambiguous).length<2)rejectionReasons.push('INSUFFICIENT_NUMERIC_ROWS');if(prose>Math.max(3,below.length/2))rejectionReasons.push('NARRATIVE_DENSITY');const tableLike=rejectionReasons.length===0;return {pageNumber:heading.pageNumber,heading,startY:heading.y,endY,lines:below,unit:resolvePdfUnit(below.slice(0,5).map(x=>x.text).join(' ')),headers,numericClusters:clusters,rows:table.rows,tableLike,confidence:tableLike&&heading.strength>=8?'HIGH':tableLike?'MEDIUM':'LOW',rejectionReasons}}
const numericPattern=/^\(?[-−]?(?:\d{1,3}(?:,\d{3})+|\d+(?:\.\d+)?)(?:[a-z%])?\)?$/i
export function adaptivePdfLines(items:PdfTextItem[],factor=0.35){const heights=items.map(x=>x.height).filter(x=>x>0);const median=heights.sort((a,b)=>a-b)[Math.floor(heights.length/2)]||8;return groupPdfLines(items,Math.max(1.5,Math.min(5,median*factor)))}
export function parsePdfNumber(raw:string){const s=raw.trim().replace(/−/g,'-');if(!numericPattern.test(s))return null;const negative=/^\(.*\)$/.test(s);const clean=s.replace(/[(),]/g,'').replace(/%$/,'');const n=Number(clean);return Number.isFinite(n)?(negative?-Math.abs(n):n):null}
export function numericTokens(line:PdfLine):PdfNumberToken[]{return line.items.flatMap(item=>{const value=parsePdfNumber(item.text);return value==null?[]:[{...item,value,raw:item.text}]})}
export function clusterNumericColumns(lines:PdfLine[],minCount=3):PdfColumnCluster[]{const xs=lines.flatMap(line=>numericTokens(line)).map(x=>x.x+x.width/2).sort((a,b)=>a-b);const clusters:PdfColumnCluster[]=[];for(const x of xs){const existing=clusters.find(c=>Math.abs(c.center-x)<=18);if(existing){existing.center=(existing.center*existing.count+x)/(existing.count+1);existing.min=Math.min(existing.min,x);existing.max=Math.max(existing.max,x);existing.count++}else clusters.push({center:x,min:x,max:x,count:1,kind:'numeric'})}return clusters.filter(x=>x.count>=minCount).sort((a,b)=>a.center-b.center)}
export function detectYearHeaders(lines:PdfLine[],years=[2025,2024,2023]):PdfYearHeader[]{const out:PdfYearHeader[]=[];for(const line of lines){for(const year of years){for(const item of line.items.filter(x=>new RegExp(`(^|\\D)${year}($|\\D)`).test(x.text))){const xCenter=item.x+item.width/2;if(!out.some(x=>x.year===year&&Math.abs(x.headerY-line.y)<4&&Math.abs(x.xCenter-xCenter)<8))out.push({year,xCenter,headerY:line.y,rawHeaderText:line.text})}}}return out.sort((a,b)=>a.headerY-b.headerY||a.xCenter-b.xCenter)}
export function bindUnit(lines:PdfLine[],pageNumber:number){const text=lines.filter(x=>x.pageNumber===pageNumber).map(x=>x.text).join(' ');return resolvePdfUnit(text)}
export function detectScope(text:string):'CONSOLIDATED'|'SEPARATE'|'UNKNOWN'{if(/consolidated|מאוחד|מאוחדים|מאוחדות|×ž××•×—×“|×ž××•×—×“×™×|×“×•×—×•×ª ×ž××•×—×“×™×/i.test(text))return 'CONSOLIDATED';if(/separate|נפרד|נפרדים|נפרדות|× ×¤×¨×“×™×|×“×•×—×•×ª × ×¤×¨×“×™×/i.test(text))return 'SEPARATE';return 'UNKNOWN'}
export function reconstructGeometryTable(pageNumber:number,lines:PdfLine[],section='OTHER'):PdfGeometryTable{const headers=detectYearHeaders(lines);const columns=clusterNumericColumns(lines,2);const rows:PdfGeometryRow[]=[];for(const line of lines){const nums=numericTokens(line);if(!nums.length)continue;const label=line.items.filter(x=>parsePdfNumber(x.text)==null).map(x=>x.text).join(' ').trim();if(!label)continue;const values:Record<number,number|null>={};let ambiguous=nums.some(token=>/^\d$/.test(token.raw.trim())&&nums.length>2);for(const token of nums){const distances=headers.map(h=>({year:h.year,d:Math.abs(token.x+token.width/2-h.xCenter)})).sort((a,b)=>a.d-b.d);if(!distances.length||distances[0].d>45||(distances[1]&&distances[1].d-distances[0].d<6)){ambiguous=true;continue}values[distances[0].year]=token.value}rows.push({label,labelFragments:[label],y:line.y,numericTokens:nums,values,ambiguous})}return {pageNumber,section,scope:detectScope(lines.map(x=>x.text).join(' ')),unit:bindUnit(lines,pageNumber),headers,columns,rows,evidence:headers.map(x=>`header ${x.year} x=${x.xCenter.toFixed(2)} y=${x.headerY.toFixed(2)})`)} }
export function reconstructWrappedLabels(lines:PdfLine[],labelX:number):PdfLine[]{const out:PdfLine[]=[];for(const line of lines){const nums=numericTokens(line);if(nums.length||!line.items.length){out.push(line);continue}const x=line.items[0].x;if(Math.abs(x-labelX)<45&&out.length&&out[out.length-1].items.every(i=>parsePdfNumber(i.text)==null)){out[out.length-1]={...out[out.length-1],text:`${out[out.length-1].text} ${line.text}`.trim(),items:[...out[out.length-1].items,...line.items]}}else out.push(line)}return out}
export function resolvePdfYearColumn(headers:string[],year:number){const found=headers.map((text,index)=>({text,index})).filter(x=>new RegExp(`(^|\\D)${year}($|\\D)`).test(x.text));return found.length===1?found[0]:null}
export function resolvePdfUnit(text:string){const s=text.toLocaleLowerCase();if(/אלפי|thousands|000/.test(s))return 'THOUSANDS_ILS';if(/מיליוני|millions/.test(s))return 'MILLIONS_ILS';if(/שח|nis|₪/.test(s))return 'ILS';return null}
export function rtlAwareTokens(items:PdfTextItem[]){return [...items].sort((a,b)=>a.y-b.y||a.x-b.x).map(x=>x.text)}
export function explicitTotalLeaseCash(label:string){return /total.*lease.*cash|lease.*payments.*total|סך.*תשלומי.*חכיר/i.test(label)}
export function canDeriveAdjustedFcf(cfo:number|null,capex:number|null,totalLeaseCash:number|null){return cfo!=null&&capex!=null&&totalLeaseCash!=null}
