export type ExpandedIssuer={canonicalId:string;displayName:string;mayaCompanyId:number;mayaReportsUrl:string;taseSecurityId:number;taseSymbol:string;business:string;sectorGroup:string;existingClass:string|null;fv2Compatibility:'FV2_COMPATIBLE'|'FV2_PROFILE_MISSING'|'FV2_NOT_YET_APPROPRIATE';status:'MARKET_MAPPING_PENDING'}
export const mayaReportsUrl=(mayaCompanyId:number,fromDate='2020-01-01',toDate='2026-09-21')=>`https://maya.tase.co.il/he/reports/companies?fromDate=${encodeURIComponent(fromDate)}&toDate=${encodeURIComponent(toDate)}&isPriority=false&isTradeHalt=false&by=company&companyId=${mayaCompanyId}&eventsFamilyIds%5B%5D=100`
export const EXPANDED_ISSUERS:ExpandedIssuer[]=[
 {canonicalId:'strauss',displayName:'Strauss Group',mayaCompanyId:746,mayaReportsUrl:mayaReportsUrl(746),taseSecurityId:746016,taseSymbol:'שטרס',business:'Branded food, beverages and consumer staples',sectorGroup:'Branded Consumer',existingClass:'CONSUMER_DEFENSIVE_BRANDED',fv2Compatibility:'FV2_COMPATIBLE',status:'MARKET_MAPPING_PENDING'},
 {canonicalId:'fox',displayName:'Fox-Wizel',mayaCompanyId:1140,mayaReportsUrl:mayaReportsUrl(1140),taseSecurityId:1087022,taseSymbol:'פוקס',business:'Apparel and lifestyle retail',sectorGroup:'Apparel Retail',existingClass:null,fv2Compatibility:'FV2_PROFILE_MISSING',status:'MARKET_MAPPING_PENDING'},
 {canonicalId:'max-stock',displayName:'Max Stock',mayaCompanyId:1815,mayaReportsUrl:mayaReportsUrl(1815),taseSecurityId:1168558,taseSymbol:'מקסו',business:'Discount and general merchandise retail',sectorGroup:'General Merchandise Retail',existingClass:null,fv2Compatibility:'FV2_PROFILE_MISSING',status:'MARKET_MAPPING_PENDING'},
 {canonicalId:'delta-israel-brands',displayName:'Delta Israel Brands',mayaCompanyId:1858,mayaReportsUrl:mayaReportsUrl(1858),taseSecurityId:1173699,taseSymbol:'דלתי',business:'Apparel, underwear and branded retail',sectorGroup:'Apparel Retail',existingClass:null,fv2Compatibility:'FV2_PROFILE_MISSING',status:'MARKET_MAPPING_PENDING'},
 {canonicalId:'castro',displayName:'Castro Model',mayaCompanyId:280,mayaReportsUrl:mayaReportsUrl(280),taseSecurityId:280016,taseSymbol:'קסטרו',business:'Fashion and apparel retail',sectorGroup:'Apparel Retail',existingClass:null,fv2Compatibility:'FV2_PROFILE_MISSING',status:'MARKET_MAPPING_PENDING'},
 {canonicalId:'diplomat',displayName:'Diplomat Holdings',mayaCompanyId:1867,mayaReportsUrl:mayaReportsUrl(1867),taseSecurityId:1173491,taseSymbol:'דיפל',business:'Import, marketing and distribution of consumer products',sectorGroup:'Consumer Distribution',existingClass:'FOOD_DISTRIBUTION',fv2Compatibility:'FV2_NOT_YET_APPROPRIATE',status:'MARKET_MAPPING_PENDING'},
 {canonicalId:'victory',displayName:'Victory Supermarket Chain',mayaCompanyId:1583,mayaReportsUrl:mayaReportsUrl(1583),taseSecurityId:1123777,taseSymbol:'וקטר',business:'Food retail and supermarkets',sectorGroup:'Food Retail',existingClass:'FOOD_RETAIL',fv2Compatibility:'FV2_COMPATIBLE',status:'MARKET_MAPPING_PENDING'},
 {canonicalId:'tiv-taam',displayName:'Tiv Taam Holdings',mayaCompanyId:103,mayaReportsUrl:mayaReportsUrl(103),taseSecurityId:103010,taseSymbol:'טטעמ',business:'Food retail and supermarkets',sectorGroup:'Food Retail',existingClass:'FOOD_RETAIL',fv2Compatibility:'FV2_COMPATIBLE',status:'MARKET_MAPPING_PENDING'},
 {canonicalId:'isrotel',displayName:'Isrotel',mayaCompanyId:1032,mayaReportsUrl:mayaReportsUrl(1032),taseSecurityId:1080985,taseSymbol:'ישרטל',business:'Hotel chain and tourism',sectorGroup:'Hotels',existingClass:null,fv2Compatibility:'FV2_NOT_YET_APPROPRIATE',status:'MARKET_MAPPING_PENDING'},
 {canonicalId:'dan-hotels',displayName:'Dan Hotels',mayaCompanyId:822,mayaReportsUrl:mayaReportsUrl(822),taseSecurityId:822015,taseSymbol:'דן',business:'Hotels and tourism',sectorGroup:'Hotels',existingClass:null,fv2Compatibility:'FV2_NOT_YET_APPROPRIATE',status:'MARKET_MAPPING_PENDING'},
]
export const expandedCanonicalIds=()=>EXPANDED_ISSUERS.map(x=>x.canonicalId)
