export type AuditRule={ruleId:string;points:number|null;maxPoints:number;available:boolean;value:number|string|null}
export type AuditDimension={score:number|null;maxScore:number;rawPoints:number;availableMax:number;rules:AuditRule[]}

export const ruleContribution=(dimension:AuditDimension,rule:AuditRule,total:number|null)=>({ruleId:rule.ruleId,points:rule.points,maxPoints:rule.maxPoints,percentOfDimension:rule.points!=null&&dimension.score!=null&&dimension.score!==0?rule.points/dimension.score*100:null,percentOfTotal:rule.points!=null&&total!=null&&total!==0?rule.points/total*100:null,available:rule.available})
export const thresholdDistance=(value:number,thresholds:number[],currentPoints:number,nextUpPoints:number|null,nextDownPoints:number|null)=>{const sorted=[...thresholds].sort((a,b)=>a-b),up=sorted.find(t=>t>value)??null,down=[...sorted].reverse().find(t=>t<=value)??null;return {value,currentThreshold:down,nextHigherThreshold:up,absoluteDistanceToNextHigher:up==null?null:up-value,absoluteDistanceToCurrent:down==null?null:value-down,pointsAtCurrentBand:currentPoints,pointsIfNextBandUp:nextUpPoints,pointsIfNextBandDown:nextDownPoints}}
export const epsilonShock=(value:number,epsilon:number,scoreAt:(x:number)=>number|null)=>({below:scoreAt(value-epsilon),baseline:scoreAt(value),above:scoreAt(value+epsilon),epsilon})
export const removeRule=(dimension:AuditDimension,ruleId:string)=>{const rules=dimension.rules.filter(r=>r.ruleId!==ruleId),availableMax=rules.filter(r=>r.available).reduce((s,r)=>s+r.maxPoints,0),rawPoints=rules.reduce((s,r)=>s+(r.points??0),0),score=availableMax/dimension.maxScore>=.6?rawPoints/availableMax*dimension.maxScore:null;return {score,availableMax,rawPoints,status:score==null?'INSUFFICIENT_EVIDENCE':'AVAILABLE'}}
export const hypotheticalWeights=(dimensions:Record<string,AuditDimension>,weights:Record<string,number>)=>Object.fromEntries(Object.entries(dimensions).map(([key,d])=>[key,d.score==null?null:d.score/d.maxScore*weights[key]]))
export const pearson=(a:number[],b:number[])=>{if(a.length!==b.length||a.length<2)return null;const ma=a.reduce((s,x)=>s+x,0)/a.length,mb=b.reduce((s,x)=>s+x,0)/b.length;const num=a.reduce((s,x,i)=>s+(x-ma)*(b[i]-mb),0),da=Math.sqrt(a.reduce((s,x)=>s+(x-ma)**2,0)),db=Math.sqrt(b.reduce((s,x)=>s+(x-mb)**2,0));return da&&db?num/(da*db):null}
export const stats=(values:number[])=>{const s=[...values].sort((a,b)=>a-b),mean=values.reduce((a,b)=>a+b,0)/values.length,med=s[Math.floor((s.length-1)/2)],variance=values.reduce((a,b)=>a+(b-mean)**2,0)/values.length;return {min:s[0],max:s.at(-1),mean,median:med,standardDeviation:Math.sqrt(variance),coefficientOfVariation:mean!==0?Math.sqrt(variance)/Math.abs(mean):null}}
