export type ComparisonStatus = 'EXACT_MATCH' | 'ROUNDING_MATCH' | 'RESTATED_MATCH' | 'RECLASSIFIED_MATCH' | 'MISMATCH' | 'INSUFFICIENT_EVIDENCE'
export type SourceUnit = 'MILLIONS' | 'THOUSANDS' | 'UNITS'
export interface ReconciliationSource { type: string; rawValue: number; unit: SourceUnit | null; normalizedILSm: number | null; scope?: string | null }
export interface ReconciliationEvidence { field:string; fiscalYear:number; sourceA:ReconciliationSource; sourceB:ReconciliationSource; toleranceBasis:string; roundingUnit:SourceUnit|null; roundingStepILSm:number|null; acceptedLowerBound:number|null; acceptedUpperBound:number|null; status:ComparisonStatus; canonicalValue:number|null; reason:string; preciseSourceType:string|null; corroboratingSourceType:string|null; comparativeReportId?:string|null; restatementEvidence?:string|null }
const step=(u:SourceUnit|null)=>u==='MILLIONS'?1:u==='THOUSANDS'?.001:u==='UNITS'?.000001:null
const norm=(v:number,u:SourceUnit|null)=>u==='MILLIONS'?v:u==='THOUSANDS'?v/1000:u==='UNITS'?v/1000000:null
export function reconcileValues(input:{field:string;fiscalYear:number;sourceA:ReconciliationSource;sourceB:ReconciliationSource;sameSemantics?:boolean;restatementEvidence?:string|null;reclassificationEvidence?:string|null;comparativeReportId?:string|null}):ReconciliationEvidence {
 const a={...input.sourceA,normalizedILSm:input.sourceA.normalizedILSm??norm(input.sourceA.rawValue,input.sourceA.unit)},b={...input.sourceB,normalizedILSm:input.sourceB.normalizedILSm??norm(input.sourceB.rawValue,input.sourceB.unit)}
 const precise=a.unit==='THOUSANDS'||a.unit==='UNITS'?a:b.unit==='THOUSANDS'||b.unit==='UNITS'?b:null; const coarse=precise===a?b:precise===b?a:null; const s=coarse?step(coarse.unit):null; const lo=coarse?.normalizedILSm!=null&&s!=null?coarse.normalizedILSm-s/2:null; const hi=coarse?.normalizedILSm!=null&&s!=null?coarse.normalizedILSm+s/2:null
 let status:ComparisonStatus='INSUFFICIENT_EVIDENCE',reason='Explicit units, normalized values, and field semantics are required.'
 if(input.sameSemantics===false){status='MISMATCH';reason='Field scope or semantics differ.'} else if(a.normalizedILSm!=null&&b.normalizedILSm!=null&&a.unit&&b.unit){if(input.restatementEvidence){status='RESTATED_MATCH';reason=input.restatementEvidence}else if(input.reclassificationEvidence){status='RECLASSIFIED_MATCH';reason=input.reclassificationEvidence}else if(a.normalizedILSm===b.normalizedILSm){status='EXACT_MATCH';reason='Normalized values are exactly equal.'}else if(lo!=null&&hi!=null&&precise?.normalizedILSm!=null&&lo<=precise.normalizedILSm&&precise.normalizedILSm<hi){status='ROUNDING_MATCH';reason='Precise source is inside the explicit unit-derived half-open interval.'}else{status='MISMATCH';reason='Normalized values fall outside the explicit unit-derived interval.'}}
 const accepted=status==='EXACT_MATCH'||status==='ROUNDING_MATCH'||status==='RESTATED_MATCH'||status==='RECLASSIFIED_MATCH'; return {field:input.field,fiscalYear:input.fiscalYear,sourceA:a,sourceB:b,toleranceBasis:s==null?'No unit-derived tolerance':`Half-open interval from explicit ${coarse?.unit} display step`,roundingUnit:coarse?.unit??null,roundingStepILSm:s,acceptedLowerBound:lo,acceptedUpperBound:hi,status,canonicalValue:accepted?(precise?.normalizedILSm??a.normalizedILSm):null,reason,preciseSourceType:precise?.type??null,corroboratingSourceType:coarse?.type??null,comparativeReportId:input.comparativeReportId??null,restatementEvidence:input.restatementEvidence??input.reclassificationEvidence??null}
}
