import { classifyEarningsQuality, classifyFcfStability } from './fairValue'

export const SCORECARD_V2_VERSION = 'SCORECARD_V2_SHADOW_1' as const
type Classification = 'SOURCE_BACKED' | 'DERIVED_FROM_SOURCE_BACKED' | 'MODEL_THRESHOLD' | 'UNAVAILABLE'
type Rule = { ruleId:string; label:string; points:number|null; maxPoints:number; available:boolean; value:number|string|null; unit:string|null; thresholdBand:string|null; periodBasis:string; sourceClassification:Classification; reasons:string[] }
type Dimension = { score:number|null; maxScore:number; rawPoints:number; availableMax:number; evidenceCoverage:number; status:string; rules:Rule[] }

const n=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:null
const annual=(rows:any[])=>['2023','2024','2025'].map(y=>rows.find(r=>r.period_type==='ANNUAL'&&String(r.fiscal_year)===y)??null)
const median=(xs:number[])=>{const a=[...xs].sort((x,y)=>x-y);return a.length?a[Math.floor(a.length/2)]:null}
const rule=(ruleId:string,label:string,maxPoints:number,points:number|null,value:number|string|null,thresholdBand:string|null,periodBasis:string,sourceClassification:Classification,reasons:string[]=[]):Rule=>({ruleId,label,maxPoints,points,available:points!=null,value,unit:null,thresholdBand,periodBasis,sourceClassification,reasons})
const normalize=(rules:Rule[],maxScore:number):Dimension=>{const raw=rules.reduce((s,r)=>s+(r.points??0),0),availableMax=rules.filter(r=>r.available).reduce((s,r)=>s+r.maxPoints,0),coverage=availableMax/maxScore;const ok=coverage>=.6;return {score:ok?raw/availableMax*maxScore:null,maxScore,rawPoints:raw,availableMax,evidenceCoverage:coverage,status:ok?'AVAILABLE':'INSUFFICIENT_EVIDENCE',rules}}
const band=(v:number,bands:[number,number,string][])=>bands.find(([min])=>v>=min)??bands.at(-1)!
const scoreMargin=(v:number,klass:string)=>klass==='CONSUMER_DEFENSIVE_BRANDED'?band(v,[[.15,10,'>=15%'],[.12,8,'12-<15%'],[.09,6,'9-<12%'],[.06,4,'6-<9%'],[Number.EPSILON,2,'>0-<6%'],[-Infinity,0,'<=0']]):klass==='FOOD_RETAIL'?band(v,[[.06,10,'>=6%'],[.05,8,'5-<6%'],[.04,6,'4-<5%'],[.03,4,'3-<4%'],[Number.EPSILON,2,'>0-<3%'],[-Infinity,0,'<=0']]):band(v,[[.07,10,['>=7%'][0]],[.055,8,'5.5-<7%'],[.04,6,'4-<5.5%'],[.025,4,'2.5-<4%'],[Number.EPSILON,2,'>0-<2.5%'],[-Infinity,0,'<=0']])
const cagr=(start:number|null,end:number|null)=>start!=null&&end!=null&&start>0&&end>0?Math.pow(end/start,.5)-1:null
const cagrScore=(v:number|null,type:'revenue'|'ebit'|'ni')=>{if(v==null)return null;const bands=type==='revenue'?[[.08,6,'>=8%'],[.05,5,'5-<8%'],[.03,4,'3-<5%'],[.01,2,'1-<3%'],[0,1,'0-<1%'],[-Infinity,0,'<0%']]:type==='ebit'?[[.12,8,'>=12%'],[.08,7,'8-<12%'],[.05,5,'5-<8%'],[.02,3,'2-<5%'],[0,1,'0-<2%'],[-Infinity,0,'<0%']]:[[.12,6,'>=12%'],[.08,5,'8-<12%'],[.05,4,'5-<8%'],[.02,2,'2-<5%'],[0,1,'0-<2%'],[-Infinity,0,'<0%']];return band(v,bands as [number,number,string][])}
const mosScore=(v:number|null)=>v==null?null:band(v,[[.4,10,'>=40%'],[.3,9,'30-<40%'],[.2,8,'20-<30%'],[.1,6,'10-<20%'],[0,4,'0-<10%'],[-.1,3,'-10% to <0%'],[-.2,2,'-20% to <-10%'],[-.3,1,'-30% to <-20%'],[-Infinity,0,'<-30%']])
export function buildScorecardV2(rows:any[],market:any,fv2:any,companyClass:string,retailer:boolean){
  const ys=annual(rows), fields=(key:string)=>ys.map(r=>n(r?.[key])), revenue=fields('revenue'),ebit=fields('operating_income'),ni=fields('net_income'),cfo=fields('cash_flow_from_operations'),capex=fields('capex'),fcf=cfo.map((v,i)=>v!=null&&capex[i]!=null?v-capex[i]:null)
  const margins=ys.map((r,i)=>revenue[i]!=null&&ebit[i]!=null&&revenue[i]!>0?ebit[i]!/revenue[i]!:null), validMargins=margins.filter((v):v is number=>v!=null), medianMargin=validMargins.length===3?median(validMargins):null
  const qRules:Rule[]=[]
  if(medianMargin!=null){const x=scoreMargin(medianMargin,companyClass);qRules.push({...rule('Q_MARGIN_LEVEL','EBIT margin level',10,x[1],medianMargin,x[2],'THREE_YEAR_MEDIAN','DERIVED_FROM_SOURCE_BACKED'),unit:'ratio',sourceClassification:'MODEL_THRESHOLD'})}else qRules.push(rule('Q_MARGIN_LEVEL','EBIT margin level',10,null,null,null,'THREE_YEAR_MEDIAN','UNAVAILABLE',['MISSING_THREE_YEAR_EBIT_MARGIN']))
  if(validMargins.length===3){const spread=Math.max(...validMargins)-Math.min(...validMargins),x=spread<=.01?[8,'<=1.0pp']:spread<=.02?[6,'>1.0 to <=2.0pp']:spread<=.04?[4,'>2.0 to <=4.0pp']:spread<=.06?[2,'>4.0 to <=6.0pp']:[0,'>6.0pp'];qRules.push({...rule('Q_MARGIN_STABILITY','EBIT margin stability',8,x[0] as number,spread,x[1] as string,'THREE_YEAR_TREND','DERIVED_FROM_SOURCE_BACKED'),unit:'ratio',sourceClassification:'MODEL_THRESHOLD'})}else qRules.push(rule('Q_MARGIN_STABILITY','EBIT margin stability',8,null,null,null,'THREE_YEAR_TREND','UNAVAILABLE',['MISSING_THREE_YEAR_EBIT_MARGIN']))
  const validNi=ni.filter((v):v is number=>v!=null),niMed=validNi.length===3?median(validNi):null
  if(validNi.length===3&&validNi.every(v=>v>0)){const rr=(Math.max(...validNi)-Math.min(...validNi))/(niMed||1),x=rr<=.2?[6,'<=20%']:rr<=.4?[4,'>20 to <=40%']:rr<=.75?[2,'>40 to <=75%']:[0,'>75%'];qRules.push({...rule('Q_NET_INCOME_STABILITY','Net income stability',6,x[0] as number,rr,x[1] as string,'THREE_YEAR_TREND','DERIVED_FROM_SOURCE_BACKED'),unit:'ratio',sourceClassification:'MODEL_THRESHOLD'})}else qRules.push(rule('Q_NET_INCOME_STABILITY','Net income stability',6,null,null,null,'THREE_YEAR_TREND','UNAVAILABLE',['MISSING_OR_NON_POSITIVE_NET_INCOME']))
  const positiveEbit=ebit.filter(v=>v!=null&&v>0).length;qRules.push(rule('Q_PROFITABILITY_CONSISTENCY','Profitability consistency',6,positiveEbit===3?6:positiveEbit===2?3:positiveEbit===1?1:0,positiveEbit,'3/3, 2/3, 1/3, 0/3','THREE_YEAR_TREND','DERIVED_FROM_SOURCE_BACKED'))
  const normalizedFcf=fcf.every(v=>v!=null)?median(fcf as number[]):null, fcfStability=normalizedFcf!=null?classifyFcfStability(fcf as number[],null):'UNAVAILABLE', fcfClassPoints:any={STABLE:6,VARIABLE:3,HIGHLY_VARIABLE:0,UNAVAILABLE:null}, earningsQuality=fv2?.evidence?.earningsQuality?.classification??'UNAVAILABLE',cashRules:Rule[]=[]
  cashRules.push(rule('CF_FCF_AVAILABILITY','FCF availability & evidence',4,normalizedFcf!=null?4:null,normalizedFcf,'AVAILABLE / missing evidence', 'THREE_YEAR_MEDIAN',normalizedFcf!=null?'DERIVED_FROM_SOURCE_BACKED':'UNAVAILABLE',normalizedFcf!=null?[]:['MISSING_ANNUAL_FCF']))
  const fcfStabilityKey=String(fcfStability??'UNAVAILABLE');cashRules.push(rule('CF_FCF_STABILITY','FCF stability',6,(fcfClassPoints as Record<string,number|null>)[fcfStabilityKey],fcfStabilityKey,fcfStabilityKey,'THREE_YEAR_TREND',fcfStabilityKey==='UNAVAILABLE'?'UNAVAILABLE':'DERIVED_FROM_SOURCE_BACKED',fcfStabilityKey==='UNAVAILABLE'?['MISSING_ANNUAL_FCF']:[]))
  const qPoints:any={EXCELLENT:8,GOOD:6,MODERATE:4,WEAK:1,UNAVAILABLE:null};cashRules.push(rule('CF_CASH_CONVERSION','Cash conversion',8,qPoints[earningsQuality],earningsQuality,earningsQuality,'Phase 14 classification','DERIVED_FROM_SOURCE_BACKED',earningsQuality==='UNAVAILABLE'?['CASH_CONVERSION_UNAVAILABLE']:[]))
  const neg=fcf.some(v=>v!=null&&v<0);cashRules.push(rule('CF_NEGATIVE_FCF','Negative FCF safeguard',2,normalizedFcf==null?null:(neg?0:2),neg?1:0,'NO_NEGATIVE_YEAR / NEGATIVE_YEAR','THREE_YEAR_TREND',normalizedFcf==null?'UNAVAILABLE':'SOURCE_BACKED',normalizedFcf==null?['MISSING_ANNUAL_FCF']:[]))
  const growthRules:Rule[]=[];for(const [id,label,key,max,type] of [['G_REVENUE_CAGR','Revenue CAGR','revenue',6,'revenue'],['G_EBIT_CAGR','EBIT CAGR','ebit',8,'ebit'],['G_NET_INCOME_CAGR','Net income CAGR','ni',6,'ni']] as any[]){const values=key==='revenue'?revenue:key==='ebit'?ebit:ni,x=cagrScore(cagr(values[0],values[2]),type);growthRules.push(x?{...rule(id,label,max,x[1],cagr(values[0],values[2]),x[2],'FY2023→FY2025','DERIVED_FROM_SOURCE_BACKED'),unit:'ratio',sourceClassification:'MODEL_THRESHOLD'}:rule(id,label,max,null,null,null,'FY2023→FY2025','UNAVAILABLE',['INVALID_POSITIVE_START_END']))}
  const latest:any=ys[2] || {},cash=n(latest.cash_and_cash_equivalents),debt=n(latest.short_term_debt)!=null&&n(latest.long_term_debt)!=null?n(latest.short_term_debt)!+n(latest.long_term_debt)!:null,cap=n(market?.market_cap),nd=debt!=null&&cash!=null?debt-cash:null
  const balanceRules:Rule[]=[];if(nd!=null&&cap!=null&&cap>0){const ratio=nd/cap,x=nd<0?[9,'NET_CASH']:ratio<=.05?[8,'<=5%']:ratio<=.1?[7,'>5 to <=10%']:ratio<=.2?[5,'>10 to <=20%']:ratio<=.35?[3,'>20 to <=35%']:[0,'>35%'];balanceRules.push({...rule('B_NET_DEBT_MARKET_CAP','Net debt / market cap',9, x[0] as number,ratio,x[1] as string,'FY2025 POINT_IN_TIME','DERIVED_FROM_SOURCE_BACKED'),unit:'ratio',sourceClassification:'MODEL_THRESHOLD'})}else balanceRules.push(rule('B_NET_DEBT_MARKET_CAP','Net debt / market cap',9,null,null,null,'FY2025 POINT_IN_TIME','UNAVAILABLE',['MISSING_DEBT_CASH_OR_MARKET_CAP']))
  if(cash!=null&&cap!=null&&cap>0){const ratio=cash/cap,x=ratio>=.1?[3,'>=10%']:ratio>=.05?[2,'5-<10%']:ratio>0?[1,'>0-<5%']:[0,'0'];balanceRules.push({...rule('B_LIQUIDITY','Liquidity',3,x[0] as number,ratio,x[1] as string,'FY2025 POINT_IN_TIME','DERIVED_FROM_SOURCE_BACKED'),unit:'ratio',sourceClassification:'MODEL_THRESHOLD'})}else balanceRules.push(rule('B_LIQUIDITY','Liquidity',3,null,null,null,'FY2025 POINT_IN_TIME','UNAVAILABLE',['MISSING_CASH_OR_MARKET_CAP']))
  const leaseComplete=!retailer||ys.every(r=>n(r?.total_lease_cash_payments)!=null);balanceRules.push(rule('B_LEASE_EVIDENCE','Lease evidence completeness',3,leaseComplete?3:null,retailer?(leaseComplete?'COMPLETE':'INCOMPLETE'):'NOT_APPLICABLE_CREDIT',retailer?(leaseComplete?'COMPLETE':'INCOMPLETE'):'NOT_APPLICABLE','THREE_YEAR_TREND',leaseComplete?'SOURCE_BACKED':'UNAVAILABLE',leaseComplete?[]:['INCOMPLETE_TOTAL_LEASE_CASH_EVIDENCE']))
  const fv2Upside=n(fv2?.upside?.basePct),methods=(fv2?.methods?Object.values(fv2.methods).filter((m:any)=>m?.available).length:0),confidence=fv2?.evidence?.earningsQuality?.cashConversionConfidence?.level??fv2?.confidence?.level??'UNAVAILABLE';const valRules:Rule[]=[];const mos=mosScore(fv2Upside);valRules.push(rule('V_MOS','Margin of safety',10,mos?.[1]??null,fv2Upside,mos?.[2]??null,'FV2 upside/downside','DERIVED_FROM_SOURCE_BACKED',mos==null?['MISSING_FV2_UPSIDE']:[]));valRules.push(rule('V_METHOD_COVERAGE','Method coverage',3,methods>=3?3:methods===2?2:methods===1?0:null,methods,methods>=3?'3 methods':methods===2?'2 methods':methods===1?'1 method':'0 methods','FV2 POINT_IN_TIME',methods>0?'DERIVED_FROM_SOURCE_BACKED':'UNAVAILABLE',methods>0?[]:['NO_AVAILABLE_FV2_METHOD']));const confPoints:any={HIGH:2,MEDIUM:2,LOW:1,INSUFFICIENT:0,UNAVAILABLE:null};valRules.push(rule('V_EVIDENCE_CONFIDENCE','Valuation evidence confidence',2,confPoints[confidence],confidence,confidence,'FV2 POINT_IN_TIME','DERIVED_FROM_SOURCE_BACKED',confidence==='UNAVAILABLE'?['MISSING_FV2_CONFIDENCE']:[]))
  const dimensions={quality:normalize(qRules,30),cashFlow:normalize(cashRules,20),growth:normalize(growthRules,20),balanceSheet:normalize(balanceRules,15),valuation:normalize(valRules,15)};const list=Object.values(dimensions),availableDimensions=list.filter(d=>d.status==='AVAILABLE').length,availableMax=list.reduce((s,d)=>s+d.availableMax,0),total=availableDimensions>=4&&availableMax>=80?list.reduce((s,d)=>s+(d.score??0),0):null,evidenceConfidence=total==null?'UNAVAILABLE':availableDimensions===5&&confidence!=='LOW'?'MEDIUM':'LOW'
  return {modelVersion:SCORECARD_V2_VERSION,status:'SHADOW',available:total!=null,dimensions,total,maxTotal:100,evidenceCoverage:availableMax/100,evidenceConfidence,reasons:total==null?['TOTAL_COVERAGE_GATE_NOT_MET']:[],legacyComparison:{available:false,reason:'LEGACY_SCORECARD_NOT_API_SOURCE'}}
}
