export interface XbrlFact { concept:string; namespace:string; contextId:string; unitId:string|null; decimals:string|null; value:string|null; periodStart:string|null; periodEnd:string|null; instant:string|null; dimensions:Record<string,string> }
export type NormalizedField={value:number|null;concept:string|null;contextId:string|null;unit:string|null;rawValue:string|null;provenance:'SOURCE_BACKED'|'DERIVED_FROM_EXPLICIT_COMPONENTS'|'UNAVAILABLE'}
export interface NormalizedXbrl { revenue:number|null; grossProfit:number|null; operatingIncome:number|null; profitBeforeTax:number|null; netIncome:number|null; netIncomeAttributableToOwners:number|null; cashFlowFromOperations:number|null; totalAssets:number|null; totalLiabilities:number|null; equity:number|null; capex:number|null; cashAndCashEquivalents:number|null; shortTermDebt:number|null; longTermDebt:number|null; nonLeaseDebt:number|null; depreciationAndAmortization:number|null; leasePrincipalCash:number|null; leaseInterestCash:number|null; totalLeaseCashPayments:number|null; basis:'ANNUAL'|'QUARTER_ONLY'|'YTD'|'UNKNOWN'; mappedConcepts:Record<string,string>; provenance:Record<string,NormalizedField> }
const tag=(s:string,n:string)=>s.match(new RegExp(n+'>\\s*([^<]+)'))?.[1]?.trim()??null
export function parseXbrl(xml:string):XbrlFact[]{const contexts=new Map<string,any>();for(const m of xml.matchAll(/<context[^>]*id="([^"]+)"[\s\S]*?<\/context>/g)){contexts.set(m[1],{contextId:m[1],periodStart:tag(m[0],'startDate'),periodEnd:tag(m[0],'endDate'),instant:tag(m[0],'instant')})}const facts:XbrlFact[]=[];for(const m of xml.matchAll(/<([\w-]+):([\w-]+)\s+([^>]*?)>([\s\S]*?)<\/[\w-]+:[\w-]+>/g)){const c=/contextRef="([^"]+)"/.exec(m[3])?.[1];if(!c||!contexts.has(c))continue;const b=contexts.get(c);facts.push({concept:m[2],namespace:m[1],contextId:c,unitId:/unitRef="([^"]+)"/.exec(m[3])?.[1]??null,decimals:/decimals="([^"]+)"/.exec(m[3])?.[1]??null,value:m[4].trim(),periodStart:b.periodStart,periodEnd:b.periodEnd,instant:b.instant,dimensions:{}})}return facts}
const aliases:Record<string,string[]>={revenue:['Revenue'],grossProfit:['GrossProfit'],operatingIncome:['ProfitLossFromOperatingActivities'],profitBeforeTax:['ProfitLossBeforeTax'],netIncome:['ProfitLoss'],netIncomeAttributableToOwners:['ProfitLossAttributableToOwnersOfParent'],cashFlowFromOperations:['CashFlowsFromUsedInOperatingActivities'],totalAssets:['Assets'],totalLiabilities:['Liabilities'],equity:['Equity'],cashAndCashEquivalents:['CashAndCashEquivalents','CashAndCashEquivalentsAndShortTermInvestments'],shortTermDebt:['BorrowingsCurrent','ShorttermBorrowings','CurrentPortionOfLongtermBorrowings'],longTermDebt:['BorrowingsNoncurrent','LongtermBorrowings','NoncurrentBorrowings'],depreciationAndAmortization:['DepreciationDepletionAndAmortisation','DepreciationAndAmortisation','DepreciationAndAmortization'],leasePrincipalCash:['PaymentsOfPrincipalOnLeaseLiabilities','PaymentsForLeaseLiabilities'],leaseInterestCash:['InterestPaidOnLeaseLiabilities','InterestPaidOnLeaseObligations'],purchasePpe:['PaymentsToAcquirePropertyPlantAndEquipment','PurchaseOfPropertyPlantAndEquipment','AcquisitionsOfPropertyPlantAndEquipment'],purchaseIntangibles:['PaymentsToAcquireIntangibleAssets','PurchaseOfIntangibleAssets']}
const annualFlow=(f:XbrlFact)=>f.periodStart?.endsWith('-01-01')&&f.periodEnd?.endsWith('-12-31')
const annualInstant=(f:XbrlFact)=>f.instant?.endsWith('-12-31')
const find=(facts:XbrlFact[],key:string,kind:'flow'|'instant')=>{const xs=facts.filter(f=>f.namespace==='ifrs-full'&&aliases[key]?.includes(f.concept)&&f.value!=null);if(kind==='instant')return xs.find(annualInstant)??xs.find(f=>f.instant!=null)??null;return xs.find(annualFlow)??xs.find(f=>f.periodStart!=null&&f.periodEnd!=null)??null}
const number=(f:XbrlFact|null)=>f?.value&&f.value!=='---'&&Number.isFinite(Number(f.value))?Number(f.value)/1000000:null
export function mapNormalized(facts:XbrlFact[]):NormalizedXbrl{const result:any={},mappedConcepts:Record<string,string>={},provenance:Record<string,NormalizedField>={};const field=(key:string,kind:'flow'|'instant',transform=(v:number)=>v)=>{const f=find(facts,key,kind),v=f?transform(number(f)??0):null;result[key]=v;provenance[key]={value:v,concept:f?.concept??null,contextId:f?.contextId??null,unit:f?.unitId??null,rawValue:f?.value??null,provenance:f?'SOURCE_BACKED':'UNAVAILABLE'};if(f)mappedConcepts[key]=`${f.namespace}:${f.concept}@${f.contextId}`;return v}
for(const k of ['revenue','grossProfit','operatingIncome','profitBeforeTax','netIncome','netIncomeAttributableToOwners','cashFlowFromOperations'])field(k,'flow');for(const k of ['totalAssets','totalLiabilities','equity','cashAndCashEquivalents','shortTermDebt','longTermDebt'])field(k,'instant');field('depreciationAndAmortization','flow');field('leasePrincipalCash','flow',Math.abs);field('leaseInterestCash','flow',Math.abs)
const ppe=field('purchasePpe','flow',Math.abs),intang=field('purchaseIntangibles','flow',Math.abs);result.capex=ppe==null&&intang==null?null:(ppe??0)+(intang??0);provenance.capex={value:result.capex,concept:ppe!=null?'purchasePpe':intang!=null?'purchaseIntangibles':null,contextId:null,unit:null,rawValue:null,provenance:ppe!=null&&intang!=null?'DERIVED_FROM_EXPLICIT_COMPONENTS':result.capex==null?'UNAVAILABLE':'SOURCE_BACKED'};result.nonLeaseDebt=result.shortTermDebt!=null&&result.longTermDebt!=null?result.shortTermDebt+result.longTermDebt:null;provenance.nonLeaseDebt={value:result.nonLeaseDebt,concept:null,contextId:null,unit:null,rawValue:null,provenance:result.nonLeaseDebt!=null?'DERIVED_FROM_EXPLICIT_COMPONENTS':'UNAVAILABLE'};result.totalLeaseCashPayments=null;provenance.totalLeaseCashPayments={value:null,concept:null,contextId:null,unit:null,rawValue:null,provenance:'UNAVAILABLE'}
const annual=facts.some(annualFlow),ytd=facts.some(x=>x.periodStart?.endsWith('-01-01')&&x.periodEnd?.endsWith('-06-30')),q=facts.some(x=>x.periodStart?.endsWith('-04-01')&&x.periodEnd?.endsWith('-06-30'));return {...result,basis:annual?'ANNUAL':ytd?'YTD':q?'QUARTER_ONLY':'UNKNOWN',mappedConcepts,provenance}}
