import {executeRemoteD1Query} from './d1-transport'
type R={company_id:string;fiscal_year:number;period_id:string;report_id:string;url:string;html_url:string|null;pdf_url:string|null}
const ids=['strauss','victory','tiv-taam','fox','max-stock','delta-israel-brands','castro','diplomat','isrotel','dan-hotels']
const rows=executeRemoteD1Query<R>(`SELECT p.company_id,p.fiscal_year,p.id AS period_id,replace(p.id,p.company_id||'-maya-','') AS report_id,s.url,h.url AS html_url,pdf.url AS pdf_url FROM financial_periods p JOIN financial_sources s ON s.company_id=p.company_id AND s.report_period_end=p.period_end AND s.source_type='ANNUAL_REPORT' LEFT JOIN financial_source_attachments h ON h.source_id=s.id AND h.attachment_type='HTML' LEFT JOIN financial_source_attachments pdf ON pdf.source_id=s.id AND pdf.attachment_type='PDF' WHERE p.period_type='ANNUAL' AND p.company_id IN (${ids.map(x=>`'${x}'`).join(',')}) ORDER BY p.company_id,p.fiscal_year`)
const esc=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')
const alias=(html:string,name:string)=>{const m=new RegExp(`fieldalias=["']${esc(name)}["'][^>]*>([^<]*)<`,'i').exec(html);return m?.[1]?.trim()??null}
let htmlParsed=0,unresolved=0
for(const r of rows){let cashRaw:string|null=null;if(r.html_url){const res=await fetch(r.html_url);if(res.ok){const html=await res.text();cashRaw=alias(html,'CashEquivalentsConsolidated');if(cashRaw)htmlParsed++}}const unit=null;const cash=cashRaw&&unit?Number(cashRaw.replace(/,/g,'')):null;if(cash==null)unresolved++;console.log(JSON.stringify({company:r.company_id,fy:r.fiscal_year,reportId:r.report_id,xbrlUrl:r.url,htmlUrl:r.html_url,pdfUrl:r.pdf_url,status:cashRaw?'HTML_CANDIDATE_UNIT_UNRESOLVED':'HTML_NO_TARGET_ROW',fields:{capexPpe:null,capexIntangibles:null,totalCapex:null,cashAndCashEquivalents:cash,shortTermDebt:null,longTermDebt:null,nonLeaseDebt:null,depreciationAmortization:null,leasePrincipalCash:null,leaseInterestCash:null,cashLeasePayments:null},evidence:cashRaw?{sourceType:'MAYA_HTML',rowLabel:'CashEquivalentsConsolidated',columnHeader:null,reportedUnit:null,rawValue:cashRaw,confidence:'LOW'}:null,writes:0}))}
console.error(`SUMMARY reports=${rows.length} html=${htmlParsed} pdf=0 unresolved=${unresolved} writes=0`)
