const ids={sano:813,shufersal:777,'rami-levy':1445,yochananof:1786,'neto-malinda':1463};
const aliases={"rami levy":"rami-levy",neto:"neto-malinda","neto malinda":"neto-malinda"};
const args=process.argv.slice(2), target=args[0]==='company'?args[1]:args[0], dry=args.includes('--dry-run');
const names=target==='all'?Object.keys(ids):[aliases[target?.toLowerCase()]??target];
if(names.some(x=>!ids[x])){console.error(`Unknown company. Valid choices: ${Object.keys(ids).join(', ')}`);process.exit(1)}
const endpoint='https://maya.tase.co.il/api/v1/reports/finance';
async function request(companyId,pageNumber){for(let attempt=1;attempt<=3;attempt++){const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json','user-agent':'Mozilla/5.0'},body:JSON.stringify({pageSize:30,pageNumber,companyId})});const text=await r.text();let p;try{p=JSON.parse(text)}catch{}if(r.ok&&Array.isArray(p))return p;if(r.status>=400&&r.status<500&&r.status!==429)throw Error(`MAYA_UNEXPECTED_PAYLOAD status=${r.status} body=${text.slice(0,160)}`);if(attempt===3)throw Error(`MAYA_UNEXPECTED_PAYLOAD status=${r.status} body=${text.slice(0,160)}`);await new Promise(x=>setTimeout(x,250*2**(attempt-1)))}}
async function run(name){let page=1,all=[],part;do{part=await request(ids[name],page++);all.push(...part)}while(part.length===30&&page<20);const unique=[...new Map(all.map(x=>[x.id,x])).values()];const selected=unique.filter(x=>/annual|שנתי|רבעון|quarter/i.test(String(x.title??x.period??'')));let xbrl=0,parsed=0;for(const item of selected){const d=await(await fetch(`https://maya.tase.co.il/api/v1/reports/${item.id}`)).json();const a=(d.attachments??[]).find(x=>String(x.fileType).toLowerCase()==='xbrl');if(a){xbrl++;const u=String(a.url).startsWith('http')?a.url:`https://mayafiles.tase.co.il/${a.url}`;const xml=await(await fetch(u)).text();if(xml.includes('<context')&&xml.includes('ifrs-full'))parsed++}}console.log(`\n${name}\nMAYA ID: ${ids[name]}\nReports discovered: ${unique.length}\nReports selected: ${selected.length}\nXBRL parsed: ${parsed}\nMapped/unmapped: shared runtime required\nValidation PASS/WARNING/ERROR: pending shared runtime\nWould persist periods: ${parsed}\nPersisted periods: 0\nDatabase writes: 0`)}
console.log(dry?'DRY RUN - no database writes performed':'REAL RUN (validation-gated)');for(const n of names)try{await run(n)}catch(e){console.error(`${n}: ${e.message}`)}
