import { mkdtempSync,rmSync,writeFileSync,readFileSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { executeRemoteD1Query,executeRemoteD1Sql } from './d1-transport'
import { mapNormalized,parseXbrl,type NormalizedXbrl } from '../worker/src/xbrl'

const ids=['strauss','victory','tiv-taam','fox','max-stock','delta-israel-brands','castro','diplomat','isrotel','dan-hotels']
const dry=process.argv.includes('--dry-run'),q=(v:unknown)=>v==null?'NULL':typeof v==='number'&&Number.isFinite(v)?String(v):`'${String(v).replaceAll("'","''")}'`
type Row={company_id:string;fiscal_year:number;period_id:string;report_id:string;url:string}
const rows=executeRemoteD1Query<Row>(`SELECT p.company_id,p.fiscal_year,p.id AS period_id,replace(p.id,p.company_id||'-maya-','') AS report_id,s.url FROM financial_periods p JOIN financial_sources s ON s.company_id=p.company_id AND s.report_period_end=p.period_end AND s.source_type='ANNUAL_REPORT' WHERE p.period_type='ANNUAL' AND p.company_id IN (${ids.map(q).join(',')}) ORDER BY p.company_id,p.fiscal_year`)
const cache=mkdtempSync(join(tmpdir(),'israel-stocks-xbrl-'));const cacheMap=new Map<string,string>()
async function source(url:string){const hit=cacheMap.get(url);if(hit)return hit;for(let attempt=0;attempt<4;attempt++){const r=await fetch(url);if(r.ok){const text=await r.text();cacheMap.set(url,text);writeFileSync(join(cache,`${cacheMap.size}.xbrl`),text,'utf8');return text}if(![403,429,500,502,503,504].includes(r.status))throw new Error(`XBRL_HTTP_${r.status}`);await new Promise(x=>setTimeout(x,500*(attempt+1)))}throw new Error('XBRL_RETRY_EXHAUSTED')}
const accepted=(d:NormalizedXbrl)=>Object.entries(d.provenance).filter(([,p])=>p.value!=null&&['capex','cashAndCashEquivalents','shortTermDebt','longTermDebt','nonLeaseDebt','depreciationAndAmortization','leasePrincipalCash','leaseInterestCash','totalLeaseCashPayments'].includes(String(p))).map(([k])=>k)
try{let ok=0,failed=0;for(const row of rows){try{const data=mapNormalized(parseXbrl(await source(row.url))),fields=accepted(data),fcf=data.cashFlowFromOperations!=null&&data.capex!=null?data.cashFlowFromOperations-data.capex:null,adjusted=data.cashFlowFromOperations!=null&&data.capex!=null&&data.totalLeaseCashPayments!=null?data.cashFlowFromOperations-data.capex-data.totalLeaseCashPayments:null;console.log(JSON.stringify({company:row.company_id,fy:row.fiscal_year,reportId:row.report_id,capexPpe:data.provenance.purchasePpe?.value??null,capexIntangibles:data.provenance.purchaseIntangibles?.value??null,totalCapex:data.capex,cash:data.cashAndCashEquivalents,shortTermDebt:data.shortTermDebt,longTermDebt:data.longTermDebt,nonLeaseDebt:data.nonLeaseDebt,depreciationAmortization:data.depreciationAndAmortization,leasePrincipal:data.leasePrincipalCash,leaseInterest:data.leaseInterestCash,totalLeaseCash:data.totalLeaseCashPayments,fcf,adjustedFcf:adjusted,accepted:fields,status:'DRY_RUN',writes:0}));if(!dry&&fields.length){const set=(name:string,key:string)=>`${name}=COALESCE(${q((data as any)[key])},${name})`;const sql=`UPDATE financial_statements SET capex=${q(data.capex)},cash_and_cash_equivalents=${q(data.cashAndCashEquivalents)},short_term_debt=${q(data.shortTermDebt)},long_term_debt=${q(data.longTermDebt)},non_lease_debt=${q(data.nonLeaseDebt)},depreciation_and_amortization=${q(data.depreciationAndAmortization)},lease_principal_payments=${q(data.leasePrincipalCash)},lease_interest_payments=${q(data.leaseInterestCash)},total_lease_cash_payments=${q(data.totalLeaseCashPayments)} WHERE period_id=${q(row.period_id)};${Object.entries(data.provenance).filter(([,p])=>p.value!=null).map(([field,p])=>`INSERT OR REPLACE INTO financial_field_provenance(id,company_id,period_id,field,concept,context_id,unit,raw_value,normalized_value,provenance_type,created_at) VALUES(${q(`${row.period_id}-${field}`)},${q(row.company_id)},${q(row.period_id)},${q(field)},${q(p.concept)},${q(p.contextId)},${q(p.unit)},${q(p.rawValue)},${q(p.value)},${q(p.provenance)},datetime('now'));`).join('')}`;await executeRemoteD1Sql(sql)}ok++}catch(e){failed++;console.error(JSON.stringify({company:row.company_id,fy:row.fiscal_year,status:'FETCH_OR_PARSE_FAILED',error:String(e),writes:0}))} }console.error(`SUMMARY rows=${rows.length} ok=${ok} failed=${failed} dryRun=${dry} cacheEntries=${cacheMap.size}`)}finally{rmSync(cache,{recursive:true,force:true})}
