import { discoverHistoricalFinancialReports, type MayaReport } from '../worker/src/maya'
import { ingestReport } from '../worker/src/ingestion'
import type { IngestionPersistence } from '../worker/src/persistenceContract'
import { executeRemoteD1Sql } from './d1-transport'

const companies:Record<string,number>={shufersal:777,'rami-levy':1445,yochananof:1786,'neto-malinda':1463,strauss:746,victory:1583,'tiv-taam':103,fox:1140,'max-stock':1815,'delta-israel-brands':1858,castro:280,diplomat:1867,isrotel:1032,'dan-hotels':822}
const argv=process.argv.slice(2), dry=argv.includes('--dry-run'), requested=argv.filter(x=>!x.startsWith('--'))
const names=requested.length?requested:Object.keys(companies)
const q=(v:unknown)=>v==null?'NULL':typeof v==='number'&&Number.isFinite(v)?String(v):`'${String(v).replaceAll("'","''")}'`
const id=(r:MayaReport)=>`${r.companyId}-maya-${r.externalReportId}`
function select(reports:MayaReport[]){
  const out:MayaReport[]=[]
  for(const year of [2023,2024,2025]){const xs=reports.filter(r=>r.fiscalYear===year&&r.reportType==='ANNUAL'&&r.xbrlUrl);if(xs.length)out.push(xs.sort((a,b)=>String(b.publishedAt).localeCompare(String(a.publishedAt)))[0])}
  for(const year of [2025,2026]){const xs=reports.filter(r=>r.fiscalYear===year&&r.reportType==='Q2'&&r.xbrlUrl);if(xs.length)out.push(xs.sort((a,b)=>String(b.publishedAt).localeCompare(String(a.publishedAt)))[0])}
  return out
}
const persistence:IngestionPersistence={
 async begin(r){await executeRemoteD1Sql(`INSERT OR REPLACE INTO discovered_reports(id,company_id,title,url,report_date,period_end,discovered_at,status,source_type,provider,external_company_id,external_report_id,report_type,fiscal_year,published_at,report_page_url,pdf_url,html_url,xbrl_url) VALUES(${q(id(r))},${q(r.companyId)},${q(r.title)},${q(r.reportPageUrl)},${q(r.publishedAt?.slice(0,10))},${q(r.periodEnd)},${q(r.discoveredAt)},'PROCESSING','QUARTERLY_REPORT','MAYA',${q(r.externalCompanyId)},${q(r.externalReportId)},${q(r.reportType)},${q(r.fiscalYear)},${q(r.publishedAt)},${q(r.reportPageUrl)},${q(r.pdfUrl)},${q(r.htmlUrl)},${q(r.xbrlUrl)})`)},
 async fail(r,status,message){await executeRemoteD1Sql(`UPDATE discovered_reports SET status=${q(status)},processed_at=NULL WHERE id=${q(id(r))}`);console.error(`${r.companyId}/${r.externalReportId}: ${message}`)},
 async activate(r,d,validation){const pid=id(r), source=`maya-${r.externalReportId}-xbrl`, year=r.fiscalYear!, annual=d.basis==='ANNUAL', start=annual?`${year}-01-01`:d.basis==='YTD'?`${year}-01-01`:`${year}-04-01`, qt=r.reportType==='Q1'?1:r.reportType==='Q2'?2:r.reportType==='Q3'?3:null, val=(k:string)=>q((d as any)[k]);const checks=validation.map((x,i)=>`INSERT OR REPLACE INTO validation_results(id,company_id,period_id,severity,code,message,created_at) VALUES(${q(`${pid}-${x.code}-${i}`)},${q(r.companyId)},${q(pid)},${q(x.severity)},${q(x.code)},${q(x.message)},datetime('now'));`).join('');await executeRemoteD1Sql(`INSERT OR REPLACE INTO financial_sources(id,company_id,title,source_type,url,publication_date,report_period_end,retrieved_at,notes,created_at) VALUES(${q(source)},${q(r.companyId)},${q(r.title)},'QUARTERLY_REPORT',${q(r.xbrlUrl)},${q(r.publishedAt?.slice(0,10))},${q(r.periodEnd)},datetime('now'),'MAYA XBRL; selected and validated by Phase 8C final.',datetime('now'));INSERT OR REPLACE INTO financial_periods(id,company_id,fiscal_year,fiscal_quarter,period_type,period_start,period_end,report_date,currency,unit,data_status,source_ids_json,flow_basis,created_at,updated_at) VALUES(${q(pid)},${q(r.companyId)},${year},${annual?'NULL':qt??'NULL'},${q(annual?'ANNUAL':'QUARTERLY')},${q(start)},${q(r.periodEnd)},${q(r.publishedAt?.slice(0,10))},'ILS','MILLIONS','MANUALLY_NORMALIZED',${q(JSON.stringify([source]))},${q(d.basis)},datetime('now'),datetime('now'));INSERT OR REPLACE INTO financial_statements(period_id,company_id,revenue,gross_profit,operating_income,profit_before_tax,net_income,net_income_attributable_to_owners,total_assets,total_liabilities,equity,cash_flow_from_operations) VALUES(${q(pid)},${q(r.companyId)},${val('revenue')},${val('grossProfit')},${val('operatingIncome')},${val('profitBeforeTax')},${val('netIncome')},${val('netIncomeAttributableToOwners')},${val('totalAssets')},${val('totalLiabilities')},${val('equity')},${val('cashFlowFromOperations')});${checks}UPDATE discovered_reports SET status='PROCESSED',processed_at=datetime('now') WHERE id=${q(pid)}`)}
}
for(const name of names){if(companies[name]===undefined)throw Error(`Unknown company ${name}`);const reports=await discoverHistoricalFinancialReports({id:name,mayaCompanyId:companies[name]},'2023-01-01','2026-09-21');const selected=select(reports);console.log(`${name}: mayaCompanyId=${companies[name]} discovered=${reports.length} selected=${selected.map(x=>x.externalReportId).join(',')} dryRun=${dry}`);for(const r of selected){try{const result=await ingestReport(r,fetch,dry?undefined:persistence);console.log(`  ${r.externalReportId} ${r.reportType}/${result.data.basis} mapped=${result.mapped} validation=${result.validation.map(x=>x.code+':'+x.severity).join(',')} persisted=${result.persisted}`)}catch(e){console.error(`  ${r.externalReportId} BLOCKED ${e instanceof Error?e.message:e}`)}}}
