import {executeRemoteD1Query,executeRemoteD1Sql} from './d1-transport'
type Row={company_id:string;fiscal_year:number;period_id:string;source_id:string;report_id:string;url:string}
type Attachment={reportId:number;fileType:string;fileName:string|null;fileSize:number|null;url:string}
type Detail={id:number;title:string;publishDate:string;companies?:{name:string;companyId:number}[];attachments?:Attachment[]}
const dry=!process.argv.includes('--persist')
const names:Record<string,RegExp>={strauss:/שטראוס|strauss/i,victory:/ויקטורי|victory/i,'tiv-taam':/טיב.?טעם|tiv.?taam/i,fox:/פוקס|fox/i,'max-stock':/מקס.?סטוק|max.?stock/i,'delta-israel-brands':/דלתא|delta/i,castro:/קסטרו|castro/i,diplomat:/דיפלומט|diplomat/i,isrotel:/ישרוטל|isrotel/i,'dan-hotels':/דן|dan/i}
const rows=executeRemoteD1Query<Row>(`SELECT p.company_id,p.fiscal_year,p.id AS period_id,s.id AS source_id,replace(p.id,p.company_id||'-maya-','') AS report_id,s.url FROM financial_periods p JOIN financial_sources s ON s.company_id=p.company_id AND s.report_period_end=p.period_end AND s.source_type='ANNUAL_REPORT' WHERE p.period_type='ANNUAL' AND p.company_id IN (${Object.keys(names).map(x=>`'${x}'`).join(',')}) ORDER BY p.company_id,p.fiscal_year`)
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms)); const base='https://mayafiles.tase.co.il/'
async function detail(id:string){for(let attempt=0;attempt<4;attempt++){const r=await fetch(`https://maya.tase.co.il/api/v1/reports/${id}`);if(r.ok)return await r.json() as Detail;if(![403,429,500,502,503,504].includes(r.status))throw new Error(`HTTP_${r.status}`);await sleep(400*(attempt+1))}throw new Error('RETRY_EXHAUSTED')}
const q=(v:string)=>`'${v.replaceAll("'","''")}'`
let verified=0,failed=0,counts={xbrl:0,html:0,pdf:0,writes:0}
for(const row of rows){try{const d=await detail(row.report_id),issuer=d.companies?.some(c=>names[row.company_id]?.test(c.name))??false,year=d.title?.includes(String(row.fiscal_year))??false,id=d.id===Number(row.report_id),attachments=(d.attachments??[]).filter(a=>a.reportId===d.id),identityVerified=id&&issuer&&year;const mapped=attachments.map(a=>{const t=/xbrl/i.test(a.fileType)?'XBRL':/^htm/i.test(a.fileType)?'HTML':/^pdf/i.test(a.fileType)?'PDF':null;return t?{type:t,url:new URL(a.url,base).toString(),title:a.fileName,contentType:t==='HTML'?'text/html':t==='PDF'?'application/pdf':'application/xml'}:null}).filter(Boolean) as {type:string;url:string;title:string|null;contentType:string}[];if(identityVerified)verified++;for(const a of mapped){if(a.type==='XBRL')counts.xbrl++;if(a.type==='HTML')counts.html++;if(a.type==='PDF')counts.pdf++;}console.log(JSON.stringify({company:row.company_id,fy:row.fiscal_year,reportId:row.report_id,identityVerified,issuer,year,id,xbrlUrl:mapped.find(a=>a.type==='XBRL')?.url??null,htmlUrl:mapped.find(a=>a.type==='HTML')?.url??null,pdfUrl:mapped.find(a=>a.type==='PDF')?.url??null,writes:0,warnings:identityVerified?[]:['ATTACHMENT_IDENTITY_MISMATCH']}));if(!dry&&identityVerified){for(const a of mapped){await executeRemoteD1Sql(`INSERT OR IGNORE INTO financial_source_attachments(id,source_id,report_id,attachment_type,url,content_type,title,created_at) VALUES(${q(`${row.source_id}-${a.type}`)},${q(row.source_id)},${q(row.report_id)},${q(a.type)},${q(a.url)},${q(a.contentType)},${a.title?q(a.title):'NULL'},datetime('now'));`);counts.writes++}}}catch(e){failed++;console.log(JSON.stringify({company:row.company_id,fy:row.fiscal_year,reportId:row.report_id,identityVerified:false,status:'DETAIL_FAILED',error:String(e),writes:0}))}await sleep(250)}
console.error(`SUMMARY reports=${rows.length} verified=${verified} failed=${failed} xbrl=${counts.xbrl} html=${counts.html} pdf=${counts.pdf} writes=${dry?0:counts.writes} dryRun=${dry}`)
