import { executeRemoteD1Sql } from './d1-transport'
import { ingestCompany } from '../worker/src/ingestion'
import type { MayaReport } from '../worker/src/maya'
import type { IngestionPersistence } from '../worker/src/persistenceContract'

const ids:Record<string,number>={sano:813,shufersal:777,'rami-levy':1445,yochananof:1786,'neto-malinda':1463,neto:1463}
const args=process.argv.slice(2),dry=args.includes('--dry-run'),name=(args[0]==='company'?args[1]:args[0])?.toLowerCase().replaceAll('_','-')
if(!name||ids[name]===undefined) throw Error('Use sano, shufersal, rami-levy, yochananof, or neto-malinda')
const q=(v:unknown)=>v==null?'NULL':typeof v==='number'&&Number.isFinite(v)?String(v):`'${String(v).replaceAll("'","''")}'`
const rid=(r:MayaReport)=>`${r.companyId}-maya-${r.externalReportId}`, qt=(r:MayaReport)=>r.reportType==='Q1'?1:r.reportType==='Q2'?2:r.reportType==='Q3'?3:null
const persistence:IngestionPersistence={
 async begin(r){executeRemoteD1Sql(`INSERT OR REPLACE INTO discovered_reports(id,company_id,title,url,report_date,period_end,discovered_at,status,source_type,provider,external_company_id,external_report_id,report_type,fiscal_year,published_at,report_page_url,pdf_url,html_url,xbrl_url) VALUES(${q(rid(r))},${q(r.companyId)},${q(r.title)},${q(r.reportPageUrl)},${q(r.publishedAt?.slice(0,10))},${q(r.periodEnd)},${q(r.discoveredAt)},'PROCESSING','QUARTERLY_REPORT','MAYA',${q(r.externalCompanyId)},${q(r.externalReportId)},${q(r.reportType)},${q(r.fiscalYear)},${q(r.publishedAt)},${q(r.reportPageUrl)},${q(r.pdfUrl)},${q(r.htmlUrl)},${q(r.xbrlUrl)})`)},
 async fail(r,status,message){executeRemoteD1Sql(`UPDATE discovered_reports SET status=${q(status)},processed_at=NULL WHERE id=${q(rid(r))}`);console.error(`${r.companyId} ${r.externalReportId}: ${message}`)},
 async activate(r,d,validation){const id=rid(r),source=`maya-${r.externalReportId}-xbrl`,year=r.fiscalYear??Number(r.periodEnd?.slice(0,4)),end=r.periodEnd??`${year}-12-31`,start=r.reportType==='Q1'?`${year}-01-01`:r.reportType==='Q2'?`${year}-04-01`:r.reportType==='Q3'?`${year}-07-01`:`${year}-01-01`,v=(k:string)=>q((d as any)[k]),checks=validation.map((x,i)=>`INSERT OR REPLACE INTO validation_results(id,company_id,period_id,severity,code,message,created_at) VALUES(${q(`${id}-${x.code}-${i}`)},${q(r.companyId)},${q(id)},${q(x.severity)},${q(x.code)},${q(x.message)},datetime('now'));`).join('');executeRemoteD1Sql(`INSERT OR REPLACE INTO financial_sources(id,company_id,title,source_type,url,publication_date,report_period_end,retrieved_at,notes,created_at) VALUES(${q(source)},${q(r.companyId)},${q(r.title)},'QUARTERLY_REPORT',${q(r.xbrlUrl)},${q(r.publishedAt?.slice(0,10))},${q(end)},datetime('now'),'Deterministically parsed MAYA XBRL.',datetime('now'));INSERT OR REPLACE INTO financial_periods(id,company_id,fiscal_year,fiscal_quarter,period_type,period_start,period_end,report_date,currency,unit,data_status,source_ids_json,flow_basis,created_at,updated_at) VALUES(${q(id)},${q(r.companyId)},${year},${qt(r)},${q(r.reportType==='ANNUAL'?'ANNUAL':'QUARTERLY')},${q(start)},${q(end)},${q(r.publishedAt?.slice(0,10))},'ILS','MILLIONS','MANUALLY_NORMALIZED',${q(JSON.stringify([source]))},${q(d.basis)},datetime('now'),datetime('now'));INSERT OR REPLACE INTO financial_statements(period_id,company_id,revenue,gross_profit,operating_income,profit_before_tax,net_income,net_income_attributable_to_owners,total_assets,total_liabilities,equity,cash_flow_from_operations) VALUES(${q(id)},${q(r.companyId)},${v('revenue')},${v('grossProfit')},${v('operatingIncome')},${v('profitBeforeTax')},${v('netIncome')},${v('netIncomeAttributableToOwners')},${v('totalAssets')},${v('totalLiabilities')},${v('equity')},${v('cashFlowFromOperations')});${checks}UPDATE discovered_reports SET status='PROCESSED',processed_at=datetime('now') WHERE id=${q(id)}`)}}
const results=await ingestCompany(name,ids[name],{dryRun:dry,persistence:dry?undefined:persistence})
console.log(`${name}: reports=${results.length} activated=${results.filter(x=>x.persisted).length} Database writes: ${dry?0:results.filter(x=>x.persisted).length}`)
if(dry) console.log('DRY RUN - no database writes performed')
