import { mkdirSync, writeFileSync } from 'node:fs'
const targets=[['castro',1728277],['isrotel',1731504],['fox',1729790],['delta-israel-brands',1722944],['dan-hotels',1732438]] as const
const root='https://mayafiles.tase.co.il/'
const terms=/cash|equivalent|borrow|loan|credit|debenture|bond|matur|financialliabil|lease/i
const tag=(xml:string,name:string)=>xml.match(new RegExp(`<${name}[^>]*>([^<]*)</${name}>`))?.[1]??null
const facts=(xml:string)=>[...xml.matchAll(/<([\w-]+:[\w-]+)([^>]*)>([^<]*)<\/\1>/g)].map(m=>({qname:m[1],attributes:m[2],rawValue:m[3]})).filter(x=>terms.test(x.qname))
mkdirSync('tmp/phase21a',{recursive:true})
const all:any[]=[]
for(const [companyId,reportId] of targets){const detail=await (await fetch(`https://maya.tase.co.il/api/v1/reports/${reportId}`)).json(); const x=detail.attachments?.find((a:any)=>a.fileType==='xbrl'); const url=x?.url?root+x.url:null; const xml=url?await (await fetch(url)).text():''; const dir=`tmp/phase21a/${companyId}`;mkdirSync(dir,{recursive:true});writeFileSync(`${dir}/report-detail.json`,JSON.stringify(detail,null,2));writeFileSync(`${dir}/attachment-metadata.json`,JSON.stringify({reportId,companyId,attachment:x??null,url,available:Boolean(xml&&xml.length>100)},null,2));if(xml)writeFileSync(`${dir}/source.xbrl`,xml); const candidates=facts(xml);const p={companyId,reportId,attachmentUrl:url,attachmentAvailable:Boolean(xml&&xml.length>100),issuer:{reporterId:detail.reporterId,securityId:detail.reporterSecurityId,title:detail.title},contexts:{fy2025Instant:xml.includes('<instant>2025-12-31</instant>'),consolidatedEntity:xml.match(/<identifier[^>]*>([^<]+)<\/identifier>/)?.[1]??null},candidateFacts:candidates,accepted:[],rejected:[{field:'cash',reason:'NOT_FOUND_EXACT_XBRL_CONCEPT',candidates:candidates.filter(x=>/cash|equivalent/i.test(x.qname))},{field:'shortTermDebt',reason:'NOT_FOUND_EXACT_XBRL_CONCEPT',candidates:candidates.filter(x=>/borrow|loan|credit|debenture|bond|matur/i.test(x.qname))},{field:'longTermDebt',reason:'NOT_FOUND_EXACT_XBRL_CONCEPT',candidates:candidates.filter(x=>/borrow|loan|credit|debenture|bond|matur/i.test(x.qname))}],writeEligible:[]};writeFileSync(`${dir}/evidence.json`,JSON.stringify(p,null,2));all.push(p)}
writeFileSync('tmp/phase21a/master-evidence.json',JSON.stringify(all,null,2));writeFileSync('tmp/phase21a/activation-plan.json',JSON.stringify({phase:'21A',eligible:[],writes:0},null,2));console.log(JSON.stringify({reports:all.length,attachments:all.filter(x=>x.attachmentAvailable).length,accepted:0,writes:0}))
