import {mkdirSync,writeFileSync,rmSync} from 'node:fs'
import {extractPdfLines} from './pdf-extract'
type Attachment={fileType:string;url:string}
const targets=[{id:'1730561',name:'Strauss',pages:[263,264],htmlCash:'535,266'},{id:'1731504',name:'Isrotel',pages:[75,76],htmlCash:null}]
const root='tmp/phase17f10';rmSync(root,{recursive:true,force:true});const out:any[]=[]
for(const target of targets){const detail=await (await fetch(`https://maya.tase.co.il/api/v1/reports/${target.id}`)).json() as {attachments?:Attachment[]};const pdf=detail.attachments?.find(x=>/^pdf/i.test(x.fileType));if(!pdf){out.push({reportId:target.id,status:'PDF_METADATA_MISSING'});continue}const response=await fetch(new URL(pdf.url,'https://mayafiles.tase.co.il/'));const all=await extractPdfLines(new Uint8Array(await response.arrayBuffer()));const lines=all.filter(x=>target.pages.includes(x.pageNumber));const dir=`${root}/${target.id}`;mkdirSync(dir,{recursive:true});writeFileSync(`${dir}/local-pages.txt`,lines.map(x=>`page=${x.pageNumber} y=${x.y.toFixed(2)} ${x.items.map(i=>`x=${i.x.toFixed(2)}:${i.text}`).join(' | ')}`).join('\n'))
  const rows=lines.filter(x=>x.items.some(i=>/\d/.test(i.text))).map(x=>({page:x.pageNumber,y:x.y,raw:x.text,items:x.items.map(i=>({x:i.x,text:i.text,width:i.width}))})).slice(0,20)
  const yearItems=lines.flatMap(x=>x.items.filter(i=>/^202[45]$/.test(i.text))).map(i=>({year:Number(i.text),x:i.x+i.width/2}));const numericXs=lines.flatMap(x=>x.items.filter(i=>/^\(?[-−]?\d[\d,.]*\)?$/.test(i.text))).map(i=>i.x+i.width/2);const noteCandidates=lines.flatMap(x=>x.items.filter(i=>/^\d{1,2}$/.test(i.text))).map(i=>({text:i.text,x:i.x+i.width/2,y:i.y}));
  const cash=lines.filter(x=>/מזומנים ושווי מזומנים|×ž×–×•×ž× ×™× ×•×©×•×•×™ ×ž×–×•×ž× ×™×/.test(x.text)).map(x=>({page:x.pageNumber,y:x.y,text:x.text,items:x.items.map(i=>({x:i.x,text:i.text}))}));
  const isrotelToken5=target.name==='Isrotel'?noteCandidates.filter(x=>x.text==='5'):[];out.push({reportId:target.id,company:target.name,pages:target.pages,unitEvidence:lines.filter(x=>/אלפי|מיליוני|ש"ח|××œ×¤×™|×ž×™×œ×™×•× ×™/.test(x.text)).slice(0,5).map(x=>({page:x.pageNumber,y:x.y,text:x.text})),yearItems,numericXRange:numericXs.length?{min:Math.min(...numericXs),max:Math.max(...numericXs)}:null,noteCandidates:noteCandidates.slice(0,30),rows,cash,isrotelToken5,htmlCash:target.htmlCash,confidence:'LOW',accepted:false,reason:'Local pages do not yet prove one authoritative table with complete unit/year/note binding'})}
writeFileSync(`${root}/results.json`,JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))
