import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { apiGet } from './api/client'
import { blockerCategory, valuationCoverage } from './lib/valuationCoverage'

const IDS=['sano','shufersal','rami-levy','yochananof','neto-malinda','strauss','victory','tiv-taam','fox','max-stock','delta-israel-brands','castro','diplomat','isrotel','dan-hotels']
const CLASS:Record<string,string>={sano:'Consumer Branded',shufersal:'Food Retail','rami-levy':'Food Retail',yochananof:'Food Retail',victory:'Food Retail','tiv-taam':'Food Retail','neto-malinda':'Distribution',strauss:'Consumer Branded',diplomat:'Distribution',fox:'Apparel Retail','delta-israel-brands':'Apparel Retail',castro:'Apparel Retail',isrotel:'Hotels','dan-hotels':'Hotels','max-stock':'Unsupported / Provisional'}
const show=(v:any)=>v==null?"UNAVAILABLE":typeof v==="number"?v.toLocaleString("en-US",{maximumFractionDigits:2}):String(v)
const load=(id:string)=>Promise.all([apiGet<any>(`/api/companies/${id}/market/latest`),apiGet<any>(`/api/companies/${id}/fair-value`),apiGet<any>(`/api/companies/${id}/scorecard-v2`)]).then(([m,f,s])=>({market:m.market,fv:f,score:s})).catch(()=>({error:true}))
export function CompleteComparePage(){const [params,setParams]=useSearchParams();const selected=[...new Set((params.get('companies')??'').split(',').map(x=>x.trim().toLowerCase()).filter(x=>IDS.includes(x)))].slice(0,4);const [data,setData]=useState<Record<string,any>>({});useEffect(()=>{Promise.all(selected.map(id=>load(id).then(x=>[id,x] as const))).then(x=>setData(Object.fromEntries(x)))},[selected.join(',')]);useEffect(()=>{const canonical=selected.join(',');if(canonical!==(params.get('companies')??''))setParams(canonical?{companies:canonical}:{})},[selected.join(',')]);if(selected.length<2)return <div className="panel empty"><h1>Compare companies</h1><p>{selected.length?'Select at least 2 companies.':'No valid companies selected.'}</p><Link className="text-link" to="/companies">Back to discovery</Link></div>;const row=(name:string,get:(d:any,id:string)=>any)=><tr key={name}><th>{name}</th>{selected.map(id=><td key={id} dir="ltr">{show(get(data[id]??{},id))}</td>)}</tr>;return <><div className="section-heading"><div className="eyebrow">COMPARISON</div><h1>Compare companies</h1><p>{selected.join(' · ')}</p></div><div className="panel"><Link className="text-link" to="/companies">Back to discovery</Link></div><div className="panel" style={{overflowX:'auto'}}><table><thead><tr><th>Metric</th>{selected.map(id=><th key={id}>{id}</th>)}</tr></thead><tbody>{row('Business Class',(_,id)=>CLASS[id])}{row('Price',d=>d.market?.currentPrice)}{row('Market Cap',d=>d.market?.marketCap)}{row('Revenue',d=>d.fv?.normalization?.revenue?.value)}{row('EBIT',d=>d.fv?.normalization?.ebit?.value)}{row('Net Income',d=>d.fv?.normalization?.netIncome?.value)}{row('CFO',d=>d.fv?.normalization?.cfo?.value)}{row('FCF',d=>d.fv?.normalization?.fcf?.value)}{row('P/E',d=>d.fv?.methods?.pe?.available?d.fv.methods.pe.value:`Unavailable: ${blockerCategory(d.fv?.methods?.pe?.reason)}`)}{row('EV/EBIT',d=>d.fv?.methods?.evEbit?.available?d.fv.methods.evEbit.value:`Unavailable: ${blockerCategory(d.fv?.methods?.evEbit?.reason)}`)}{row('FCF Yield',d=>d.fv?.methods?.fcf?.available?'AVAILABLE':`Unavailable: ${blockerCategory(d.fv?.methods?.fcf?.reason)}`)}{row('Valuation Coverage',d=>{const c=valuationCoverage(d.fv?.methods);return `${c.availableMethods}/3 ${c.label}`})}{row('FV1',d=>d.fv?.valuationScore?.available?d.fv.perShare?.base:null)}{row('FV2',d=>d.fv?.fv2?.available?d.fv.fv2.perShare?.base:null)}{row('Scorecard V2',d=>d.score?.total)}{row('Scorecard Coverage',d=>d.score?.dimensions?`${Object.values(d.score.dimensions).filter((x:any)=>x?.status==='AVAILABLE').length} / 5`:null)}{row('Quality',d=>d.score?.dimensions?.quality?.score)}{row('Cash',d=>d.score?.dimensions?.cash?.score)}{row('Growth',d=>d.score?.dimensions?.growth?.score)}{row('Balance',d=>d.score?.dimensions?.balance?.score)}{row('Valuation',d=>d.score?.dimensions?.valuation?.score)}</tbody></table></div></>}
