import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiFinancialRepository } from './data/apiRepository'
import './LiveApiCompanyPage.css'

const reasons:Record<string,string>={MISSING_NET_DEBT_INPUTS:'חסרים נתוני חוב נטו',MISSING_EBITDA:'חסר EBITDA',MISSING_EBIT:'חסר EBIT',MISSING_FCF:'חסר תזרים חופשי',NON_POSITIVE_FCF:'תזרים חופשי אינו חיובי',MISSING_LEASE_CASH_PAYMENTS:'חסרים תשלומי חכירה במזומן',TTM_NOT_AVAILABLE:'TTM אינו זמין',INCOMPATIBLE_IFRS16_BASIS:'בסיס IFRS 16 אינו תואם',MISSING_NET_INCOME:'חסר רווח נקי',NON_POSITIVE_NET_INCOME:'רווח נקי אינו חיובי',MARKET_DATA_UNAVAILABLE:'נתוני שוק אינם זמינים'}
const num=(v:unknown,d=2)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):'לא זמין'
const ltr=(v:unknown,d=2)=><span dir="ltr" className="financial-number">{num(v,d)}</span>
const price=(v:unknown)=><span dir="ltr" className="financial-number">{typeof v==='number'?`₪${v.toFixed(2)}`:'לא זמין'}</span>
const marketCap=(v:unknown)=><span dir="ltr" className="financial-number">{typeof v==='number'?(v>=1000?`₪${(v/1000).toFixed(2)} מיליארד`:`₪${v.toFixed(1)} מיליון`):'לא זמין'}</span>
const basis=(v:string|undefined)=>v==='LATEST_ANNUAL'?'שנה מלאה אחרונה':v==='TTM'?'12 החודשים האחרונים':v==='QUARTER_ONLY'?'רבעון בלבד':'לא זמין'
function Metric({label,value,reason}:{label:string;value:React.ReactNode;reason?:string}){return <div className="valuation-metric"><span>{label}</span><strong>{value}</strong>{reason&&<small>{reason}</small>}</div>}
function MarketValuation({market}:{market:any}){const v=market?.valuation;const unavailable=(key:string)=>v?.[key]==null?(v?.unavailableReasons??[]).map((x:string)=>reasons[x]??'נתון חסר').find(Boolean):undefined;if(!market)return <section className="panel live-market"><h2>נתוני שוק</h2><p>אין נתוני שוק</p></section>;return <><section className="panel live-market"><div className="section-heading"><h2>נתוני שוק</h2><span className="live-status">נתוני תמחור זמינים</span></div><div className="market-cards"><Metric label="מחיר אחרון" value={price(market.share_price)}/><Metric label="שווי שוק" value={marketCap(market.market_cap)}/><Metric label="שינוי יומי" value={<span dir="ltr" className={market.day_change>=0?'positive financial-number':'negative financial-number'}>{market.day_change==null?'לא זמין':`${market.day_change<0?'-':''}₪${Math.abs(market.day_change).toFixed(2)} (${market.day_change_pct==null?'—':`${market.day_change_pct.toFixed(2)}%`})`}</span>}/></div><div className="market-meta">מקור: <b>{market.provider==='GLOBES'?'Globes':market.provider}</b> · השהיה: ~15 דקות · עדכון: <span dir="ltr">{market.as_of??'—'}</span></div></section><section className="panel valuation-panel"><div className="section-heading"><h2>מכפילי תמחור</h2><span className="score-status">נתוני תמחור זמינים · ציון התמחור /15 עדיין לא הופעל</span></div><div className="valuation-grid"><Metric label="P/E" value={v?.pe==null?'לא זמין':<>{ltr(v.pe)}×</>} reason={unavailable('pe')}/><Metric label="EV" value={marketCap(v?.enterpriseValueIlsMillions)}/><Metric label="EV / EBIT" value={v?.evEbit==null?'לא זמין':<>{ltr(v.evEbit)}×</>} reason={unavailable('evEbit')}/><Metric label="EV / EBITDA" value={v?.evEbitda==null?'לא זמין':<>{ltr(v.evEbitda)}×</>} reason={unavailable('evEbitda')}/><Metric label="EV / EBITDA ex IFRS 16" value="לא זמין" reason="בסיס IFRS 16 אינו תואם"/><Metric label="P / FCF" value={v?.priceToFcf==null?'לא זמין':<>{ltr(v.priceToFcf)}×</>} reason={unavailable('priceToFcf')}/><Metric label="FCF Yield" value={v?.fcfYield==null?'לא זמין':<>{ltr(v.fcfYield*100)}%</>} reason={unavailable('fcfYield')}/><Metric label="Net Debt / Market Cap" value={v?.netDebtToMarketCap==null?'לא זמין':<>{ltr(v.netDebtToMarketCap*100)}%</>} reason={unavailable('netDebtToMarketCap')}/><Metric label="Net Cash / Market Cap" value={v?.netCashToMarketCap==null?'לא זמין':<>{ltr(v.netCashToMarketCap*100)}%</>} reason={unavailable('netCashToMarketCap')}/></div><div className="basis-note">בסיס רווח: {basis(v?.basis?.earnings)} · תקופה: <span dir="ltr">{v?.periodEnd??'לא זמין'}</span></div></section></>}
export function LiveApiCompanyPage({id}:{id:string}){const [state,setState]=useState<any>();const [error,setError]=useState(false);useEffect(()=>{Promise.all([apiFinancialRepository.getCompany(id),apiFinancialRepository.getAnnualFinancials(id),apiFinancialRepository.getQuarterlyFinancials(id),apiFinancialRepository.getSources(id),apiFinancialRepository.getMarketSnapshot(id)]).then(([company,annual,quarterly,sources,market])=>setState({company,periods:[...annual,...quarterly],sources,market})).catch(()=>setError(true))},[id]);if(error)return <div className="panel api-state"><h1>לא ניתן לטעון את נתוני החברה כרגע</h1></div>;if(!state)return <div className="panel api-state"><h1>טוען נתונים...</h1></div>;return <><div className="back-link"><Link to="/companies">חזרה לכל החברות</Link></div><div className="page-title"><div><div className="eyebrow">{state.company.ticker} / API DATA</div><h1>{state.company.name_he}</h1><p>נתונים פיננסיים ממקור API רשמי</p></div></div><MarketValuation market={state.market}/><div className="panel financial-table"><table><thead><tr><th>תקופה</th><th>הכנסות</th><th>רווח תפעולי</th><th>רווח נקי</th><th>בסיס</th></tr></thead><tbody>{state.periods.filter((p:any,i:number,a:any[])=>a.findIndex((x:any)=>`${x.periodEnd}|${x.periodType}|${x.flowBasis??''}`===`${p.periodEnd}|${p.periodType}|${p.flowBasis??''}`)===i).sort((a:any,b:any)=>String(a.periodEnd).localeCompare(String(b.periodEnd))).map((p:any)=><tr key={p.id}><td>{p.periodEnd??'—'}</td><td>{p.revenue??'—'}</td><td>{p.operatingIncome??p.operating_income??'—'}</td><td>{p.netIncome??p.net_income??'—'}</td><td>{p.flowBasis??p.flow_basis??p.periodType??'—'}</td></tr>)}</tbody></table></div></>}
