// @ts-nocheck
import {useEffect,useMemo,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {apiGet} from './api/client'
import {CompleteComparePage} from './CompleteComparePage'
import {readSavedComparisons,saveComparison,writeSavedComparisons} from './lib/savedComparisons'
import type {SavedComparisonSet} from './lib/savedComparisons'
const universe=['sano','shufersal','rami-levy','yochananof','neto-malinda','strauss','victory','tiv-taam','fox','max-stock','delta-israel-brands','castro','diplomat','isrotel','dan-hotels']
export function Phase23CComparePage(){const [params]=useSearchParams(),ids=[...new Set((params.get('companies')??'').split(',').map(x=>x.trim().toLowerCase()).filter(x=>universe.includes(x)))].slice(0,4),[sets,setSets]=useState<SavedComparisonSet[]>([]),[name,setName]=useState(''),[notice,setNotice]=useState(''),[visuals,setVisuals]=useState<Record<string,any>>({}),[sources,setSources]=useState<Record<string,any>>({});useEffect(()=>setSets(readSavedComparisons(localStorage,universe)),[]);useEffect(()=>{Promise.all(ids.map(id=>apiGet<any>(`/api/companies/${id}/fair-value`).then(f=>[id,f] as const).catch(()=>[id,null] as const))).then(x=>setVisuals(Object.fromEntries(x)));Promise.all(ids.map(id=>apiGet<any>(`/api/companies/${id}/sources`).then(s=>[id,s] as const).catch(()=>[id,null] as const))).then(x=>setSources(Object.fromEntries(x)))},[ids.join(',')]);const save=()=>{const r=saveComparison(localStorage,sets,name,ids,universe);if(r.error)setNotice(r.error);else{setSets(r.sets);setName('');setNotice('Saved locally.')}};const remove=(id:string)=>{const next=sets.filter(x=>x.id!==id);writeSavedComparisons(localStorage,next);setSets(next)};const max=Math.max(0,...ids.map(id=>Number(visuals[id]?.market?.marketCap??0)));const saved=useMemo(()=>sets,[sets]);return <><div className="panel"><h2>Saved comparisons</h2>{ids.length>=2&&<div className="filters"><input aria-label="Saved comparison name" value={name} onChange={e=>setName(e.target.value)} placeholder="Name this comparison"/><button className="filter active" onClick={save}>Save comparison</button></div>}{notice&&<p>{notice}</p>}{saved.map(s=><div className="filters" key={s.id}><strong>{s.name}</strong><small>{s.companyIds.join(' · ')}</small><Link className="filter" to={`/compare?companies=${s.companyIds.join(',')}`}>Open</Link><button className="filter" onClick={()=>remove(s.id)}>Delete</button></div>)}</div>{ids.length>=2&&<><div className="panel"><h2>Relative display scale</h2><p>Presentation-only scale; exact values remain in the comparison table.</p>{ids.map(id=>{const value=visuals[id]?.market?.marketCap;return <div key={id}><span>{id} · Market Cap: {value==null?'UNAVAILABLE':value}</span><div style={{height:8,background:'#26313d',margin:'5px 0 12px'}}><i aria-label={`${id} relative market cap`} style={{display:'block',height:8,width:max&&value?`${Math.max(0,Number(value)/max*100)}%`:'0%',background:'#7aa2f7'}}/></div></div>})}</div><div className="panel"><h2>Data provenance</h2>{ids.map(id=>{const s=sources[id];const source=s?.sources?.at?.(-1)??s?.at?.(-1);return <div key={id}><strong>{id}</strong><p>Financial period source: {source?.title??'Source metadata unavailable'}</p>{source?.url&&<a className="text-link" href={source.url} target="_blank" rel="noreferrer">Open source</a>}<p>Market source: {visuals[id]?.market?.provider??'Source metadata unavailable'} · {visuals[id]?.market?.asOf??'UNAVAILABLE'}</p></div>})}</div></>}<CompleteComparePage/></>}
