import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiGet } from './api/client'
import { canonicalCompanyId, findCompany } from './data/companies'
import { researchUniverse } from './ResearchWorkspace'
import { readResearchNotes } from './lib/researchNotes'
import { readWatchlist } from './lib/watchlist'
import { markReviewed, readReviewStates, REVIEW_STATE_EVENT, type CompanyReviewState } from './lib/reviewState'
import { valuationCoverage } from './lib/valuationCoverage'

type ReviewData = { freshness?: any; market?: any; valuation?: any; score?: any; error?: boolean }
type ReviewFilter = 'all' | 'needs' | 'reviewed' | 'filing' | 'research'
const formatDate = (value: string | null | undefined) => value ? new Date(value).toLocaleString() : 'UNAVAILABLE'
const companyLabel = (id: string) => { const company = findCompany(id); return { name: company?.name ?? id, ticker: company?.ticker ?? id.toUpperCase(), className: company?.subsector ?? 'Company research' } }
const freshnessDate = (freshness: any) => [freshness?.latestDiscoveredAt, freshness?.latestDiscovered?.publishedAt, freshness?.latestProcessedAt, freshness?.latestProcessed?.reportDate].find(value => typeof value === 'string' && !Number.isNaN(Date.parse(value))) as string | undefined
const statusFor = (state: CompanyReviewState | undefined, noteUpdatedAt: string | undefined, freshness: any) => {
  if (!state) return { label: 'No review yet', filter: 'needs' as ReviewFilter, reason: 'No local review timestamp yet.' }
  if (freshness?.newerReportAvailable === true) return { label: 'New filing', filter: 'filing' as ReviewFilter, reason: 'A newer source report is available.' }
  if (freshnessDate(freshness) && Date.parse(freshnessDate(freshness)!) > Date.parse(state.lastReviewedAt)) return { label: 'New filing', filter: 'filing' as ReviewFilter, reason: 'Source freshness is newer than the last review.' }
  if (noteUpdatedAt && Date.parse(noteUpdatedAt) > Date.parse(state.lastReviewedAt)) return { label: 'Research updated', filter: 'research' as ReviewFilter, reason: 'The local research note was edited after the last review.' }
  return { label: 'Reviewed', filter: 'reviewed' as ReviewFilter, reason: 'No newer source or research activity detected.' }
}

export function ReviewPage() {
  const [watchlist, setWatchlist] = useState<string[]>([]); const [states, setStates] = useState<CompanyReviewState[]>([]); const [data, setData] = useState<Record<string, ReviewData>>({}); const [filter, setFilter] = useState<ReviewFilter>('all'); const [sort, setSort] = useState('needs');
  const sync = () => { setWatchlist(readWatchlist(localStorage, researchUniverse)); setStates(readReviewStates(localStorage, researchUniverse)) }
  useEffect(() => { sync(); const events = ['storage', 'israel-stocks-watchlist-changed', REVIEW_STATE_EVENT]; events.forEach(event => window.addEventListener(event, sync)); return () => events.forEach(event => window.removeEventListener(event, sync)) }, [])
  useEffect(() => { Promise.all(watchlist.map(id => Promise.all([apiGet<any>(`/api/companies/${id}/freshness`), apiGet<any>(`/api/companies/${id}/market/latest`), apiGet<any>(`/api/companies/${id}/fair-value`), apiGet<any>(`/api/companies/${id}/scorecard-v2`)]).then(([freshness, market, valuation, score]) => [id, { freshness, market: market.market, valuation, score }] as const).catch(() => [id, { error: true }] as const))).then(rows => setData(Object.fromEntries(rows))) }, [watchlist.join(',')])
  const notes = useMemo(() => readResearchNotes(localStorage, researchUniverse), [states, watchlist.join(',')])
  const rows = watchlist.map(id => { const note = notes.find(item => item.companyId === id); const state = states.find(item => item.companyId === id); const status = statusFor(state, note?.updatedAt, data[id]?.freshness); return { id, note, state, status, details: data[id], label: companyLabel(id) } }).filter(row => filter === 'all' || row.status.filter === filter || (filter === 'needs' && row.status.filter === 'needs')).sort((a, b) => { if (sort === 'name') return a.label.name.localeCompare(b.label.name); if (sort === 'recent') return (b.state?.lastReviewedAt ?? '').localeCompare(a.state?.lastReviewedAt ?? ''); if (sort === 'oldest') return (a.state?.lastReviewedAt ?? '').localeCompare(b.state?.lastReviewedAt ?? ''); return Number(a.status.label === 'Reviewed') - Number(b.status.label === 'Reviewed') || a.label.name.localeCompare(b.label.name) })
  const review = (id: string) => { const next = markReviewed(localStorage, states, id, researchUniverse); setStates(next); window.dispatchEvent(new Event(REVIEW_STATE_EVENT)) }
  if (!watchlist.length) return <><div className="page-title"><div><div className="eyebrow">INVESTOR WORKFLOW</div><h1>Review queue</h1><p>Review is based on companies in your local watchlist.</p></div></div><div className="panel empty"><h2>No companies to review</h2><p>Add companies to your watchlist to see source freshness and research changes here.</p><Link className="filter active" to="/companies">Browse companies</Link></div></>
  return <><div className="page-title"><div><div className="eyebrow">INVESTOR WORKFLOW</div><h1>Review queue</h1><p>Neutral source and research context for your watchlist.</p></div><Link className="filter" to="/watchlist">Watchlist</Link></div><div className="filters"><select aria-label="Review filter" value={filter} onChange={e => setFilter(e.target.value as ReviewFilter)}><option value="all">All</option><option value="needs">Needs review</option><option value="reviewed">Reviewed</option><option value="filing">New filing</option><option value="research">Research updated</option></select><select aria-label="Review sort" value={sort} onChange={e => setSort(e.target.value)}><option value="needs">Needs review first</option><option value="recent">Most recently reviewed</option><option value="oldest">Least recently reviewed</option><option value="name">Company name</option></select></div><div className="review-grid">{rows.map(row => { const coverage = valuationCoverage(row.details?.valuation?.methods); return <article className="panel review-card" key={row.id}><div className="panel-head"><div><span className="ticker">{row.label.ticker}</span><h2>{row.label.name}</h2><small>{row.label.className}</small></div><span className="filter">{row.status.label}</span></div><p>{row.status.reason}</p><div className="review-meta"><span>Last reviewed: {formatDate(row.state?.lastReviewedAt)}</span><span>Research: {row.note ? `updated ${formatDate(row.note.updatedAt)} · ${row.note.catalysts.length} catalysts · ${row.note.risks.length} risks · ${row.note.questions.length} questions` : 'No note'}</span><span>Processed period: {row.details?.freshness?.latestProcessedPeriod ?? 'UNAVAILABLE'}</span><span>Discovered period: {row.details?.freshness?.latestDiscoveredPeriod ?? 'UNAVAILABLE'}</span><span>Newer report: {row.details?.freshness?.newerReportAvailable == null ? 'UNAVAILABLE' : row.details.freshness.newerReportAvailable ? 'Yes' : 'No'}</span><span>Market as-of: {row.details?.market?.asOf ?? row.details?.market?.as_of ?? 'UNAVAILABLE'}</span><span>Valuation coverage: {coverage.availableMethods}/3</span><span>Scorecard: {row.details?.score?.total ?? 'UNAVAILABLE'}</span></div><div className="filters"><Link className="filter" to={`/company/${canonicalCompanyId(row.id)}`}>Open company</Link><Link className="filter" to="/research">Research workspace</Link><button className="filter active" onClick={() => review(row.id)}>{row.state ? 'Review again' : 'Mark reviewed'}</button></div></article>})}</div></>
}
