import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { readWatchlist } from './lib/watchlist'
import { readSavedComparisons } from './lib/savedComparisons'
import { readResearchNotes } from './lib/researchNotes'
import { readReviewStates } from './lib/reviewState'
import { buildWorkspaceBackup, mergeWorkspace, parseWorkspaceBackup, serializeWorkspaceBackup, workspaceUniverse, type ParsedBackup } from './lib/workspaceBackup'

const refreshEvent = 'workspace-backup-refresh'
export function WorkspaceBackupPage() {
  const [counts, setCounts] = useState({ watchlist: 0, savedComparisons: 0, researchNotes: 0, reviewState: 0 })
  const [preview, setPreview] = useState<ParsedBackup | null>(null)
  const [mode, setMode] = useState<'merge' | 'replace'>('merge')
  const [error, setError] = useState('')
  const [result, setResult] = useState('')
  const sync = () => setCounts({ watchlist: readWatchlist(localStorage, workspaceUniverse).length, savedComparisons: readSavedComparisons(localStorage, workspaceUniverse).length, researchNotes: readResearchNotes(localStorage, workspaceUniverse).length, reviewState: readReviewStates(localStorage, workspaceUniverse).length })
  useEffect(() => { sync(); const handler = () => sync(); window.addEventListener('storage', handler); window.addEventListener(refreshEvent, handler); return () => { window.removeEventListener('storage', handler); window.removeEventListener(refreshEvent, handler) } }, [])
  const exportBackup = () => { const blob = new Blob([serializeWorkspaceBackup(buildWorkspaceBackup(localStorage))], { type: 'application/json;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); const date = new Date(); const pad = (v: number) => String(v).padStart(2, '0'); a.href = url; a.download = `israel-stocks-workspace-${date.toISOString().slice(0, 10)}-${pad(date.getHours())}${pad(date.getMinutes())}.json`; a.click(); URL.revokeObjectURL(url); setResult('Backup exported locally to your device.') }
  const onFile = async (file?: File) => { setError(''); setResult(''); setPreview(null); if (!file) return; if (file.size > 5 * 1024 * 1024) { setError('Backup file is larger than the 5 MB safety limit.'); return } try { setPreview(parseWorkspaceBackup(JSON.parse(await file.text()))) } catch (e) { setError(e instanceof Error ? e.message : 'Backup could not be read.') } }
  const apply = () => { if (!preview) return; if (mode === 'replace' && !window.confirm('This will replace your local watchlist, saved comparisons, research notes, and review state on this browser.')) return; const summary = mergeWorkspace(localStorage, preview.backup, mode); sync(); setResult(`Saved locally in this browser. Watchlist ${summary.watchlist}; comparisons ${summary.savedComparisons}; research notes ${summary.researchNotes}; review records ${summary.reviewState}.`); setPreview(null); window.dispatchEvent(new Event(refreshEvent)) }
  const previewRows = useMemo(() => preview ? [['Watchlist companies', preview.backup.appData.watchlist.length], ['Saved comparison sets', preview.backup.appData.savedComparisons.length], ['Research notes', preview.backup.appData.researchNotes.length], ['Review records', preview.backup.appData.reviewState.length]] : [], [preview])
  return <><div className="page-title"><div><div className="eyebrow">LOCAL WORKSPACE</div><h1>Backup & Restore</h1><p>Export and restore your browser-local investor workspace.</p></div><Link className="filter" to="/review">Review queue</Link></div><div className="notice">Backups stay on your device. Export is not uploaded, import is processed locally, and there is no cloud sync or account backup.</div><div className="panel"><h2>Your local workspace</h2><div className="review-meta"><span>Watchlist companies: <strong>{counts.watchlist}</strong></span><span>Saved comparisons: <strong>{counts.savedComparisons}</strong></span><span>Research notes: <strong>{counts.researchNotes}</strong></span><span>Review records: <strong>{counts.reviewState}</strong></span></div></div><div className="backup-grid"><div className="panel"><h2>Export</h2><p>Creates a versioned JSON file containing only the four supported workspace contracts.</p><button className="filter active" onClick={exportBackup}>Export workspace</button></div><div className="panel"><h2>Import</h2><p>Select a JSON backup to validate and preview it before any local mutation.</p><input aria-label="Import workspace backup" type="file" accept="application/json,.json" onChange={e => void onFile(e.target.files?.[0])} />{error && <p role="alert" className="warning-heading">{error}</p>}{preview && <div className="backup-preview"><h3>Import preview</h3>{previewRows.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}<p>{preview.invalid ? `${preview.invalid} invalid records ignored.` : 'All supported records are valid.'} Research conflicts use newer updatedAt; equal timestamps keep existing. Review conflicts use newer lastReviewedAt; equal timestamps keep existing.</p><label>Mode <select value={mode} onChange={e => setMode(e.target.value as 'merge' | 'replace')}><option value="merge">Merge</option><option value="replace">Replace workspace</option></select></label>{mode === 'replace' && <p className="warning-heading">Replace affects only the four supported local workspace keys and requires confirmation.</p>}<button className="filter active" onClick={apply}>Apply import</button></div>}</div></div>{result && <div className="notice" role="status">{result}</div>}<div className="panel"><h2>Safety</h2><p>This feature never exports arbitrary localStorage, financial data, market snapshots, valuation outputs, Scorecard payloads, API responses, provenance, credentials, or secrets. Imported content is treated as untrusted plain text.</p></div></>
}
